### ISSUE TITLE
Build fails on ARM-based Linux systems

### ISSUE THREAD

**Issue by johnblommers** [marktext/marktext#1057]
### Description

- [ x] Can you reproduce the issue? 

### Steps to reproduce

1. Follow the directions at [Mark Text Contributing Guide](https://github.com/marktext/marktext/blob/master/.github/CONTRIBUTING.md#build-instructions)
2. [cd marketext]
3. [yarn install.]

**Expected behavior:**

The command succeeds

**Actual behavior:**

```
yarn install
yarn install v1.16.0
$ node .electron-vue/preinstall.js
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.1.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/pi/Desktop/marktext/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

**Link to an example: [optional]**

### Versions

- Mark Text: v0.14
- Operating system 1: Ubuntu 16.04 64-bit installed on a pinebook64
- Operating system 2: Raspbian installed on a Raspberry Pi 3B (armv7l)

**Note* that there is nothing wrong with my network and I can ping registry.yarnpkg.com just fine.

**Comment by fxha** [comment]
Thanks @johnblommers for reporting this issue. This seems to be an issue with `yarn` or your configuration, you could try to remove `node_modules` and `yarn.lock` and try again. If the issue is still present, please report the issue to the yarn team. Depending on you location this may be an issue with the CDN, like @Jocs has a slow/bad connection too.

Please note that we don't support ARM architecture (yet). We cannot guaranty a successful build and that all components and native libraries work at runtime. Our supported platforms and architectures are:

- macOS `x64`
- Linux `x64`
- Windows `ia32` (also known as `x86`) and `x64`

It would be great if you could help to support ARM as an unofficial platform too, so other people can build Mark Text from source.
