### ISSUE TITLE
MarkText + Zettlr

### ISSUE THREAD

**Issue by StefanoCecere** [marktext/marktext#1130]
i discover MarkText right now.. very nice
and i dicovered Zettlr https://github.com/Zettlr/Zettlr yesterday.. huge!

two electron base opensource very good MD text editors, run by two very active developers!

i hope you can become friends and exchange experiences!

**Comment by Jocs** [comment]
Very good advice, I will also investigate the Zettlr project and learn about it. I also hope that we can discuss a specific issue or feature about marktext or Zettlr.

**Comment by cpp** [comment]
Knowledge management techniques (Zettelkasten) would be great to see.
sublimeless_zk (https://github.com/renerocksai/sublimeless_zk/) has also some good feautures in this direction.

**Comment by adrienbeau** [comment]
I have used those editors before choosing Mark Text.

Unfortunately [sublimeless_zk](https://github.com/renerocksai/sublimeless_zk) was abandoned very shortly after its initial development period. The author is still around, but working on other projects.

[Zettlr](https://github.com/Zettlr/Zettlr) is active, but less than Mark Text, it currently has a single developer, and a smaller community. It has significant philosophical differences to Mark Text, preferring to always show markup, being closer to the source code, rather than being WYSIWYG.

However, Zettlr knowledge management features are what sets it apart from Mark Text, and it would be great to see them adopted in Mark Text. The major features are the following:

* **File identifiers:** Files can have identifiers (the default is a timestamp, but the user can define a custom format using regexp). The identifier can be in the file name (typically users will use the id + a short description). The identifier can also be in a metadata block at the top of the document.
* **Easy links to other files:** Zettlr has a syntax to easily type links to other files `[[fileId]]`. sublimeless_zk also supports `[[fileId + short description]]` which is more legible.
* **Support for tags:** Zettlr recognizes the typical syntax for hashtags `#tag`
* **Files, identifiers and tags are indexed:** this allows Zettlr to offer many nice interactive features around those concepts (the user configures a root directory, and everything inside is indexed)
* **Search engine:** Zettlr supports searching in titles, in file contents, but also by id and by tag.

These core features are nicely combined in the UI: hovering over a file link shows a short description and an excerpt, clicking a file link opens it in a new tab, clicking a file id or tab starts a search. It also offers easy creation of new files (attributing an id, initializing the file from a template).

The use case behind all those features is the following:

* Users store their knowledge (summary of reading a paper, personal research, lists of other items) in small documents focused on one subject, one piece of knowledge
* In a document, users can easily put references to other documents (previous research, previous thoughts on the same topic) using their ID
* As they write their thoughts, users can easily create a new document in case a different idea or subject pops up (the UI does not distract them)
* Using all those features, users can also easily create lists of topics, lists of documents (using their ID), to organize their thoughts, plans, etc.
* Over time, this builds a personal knowledge base that can be very powerful

**Comment by DutchPete** [comment]
@adrienbeau : very good synopsis of Zettlr. I looked at it just before discovering Mark Text. Apart from a difference in features and philosophy between the two, Zettlr is a knowledge management app, as you mention, or, to stay in the notes terminology, a note management app, whereas MT is a note-taking/editor app. And indeed, that's why MT could be incorporated in Zettlr, theoretically.

Nevertheless, Zettlr undoubtedly has its own "MT" incorporated, and replacing that with MT would mean a major restructuring/recoding, I would think.

MT has the potential to become a best-in-class benchmark, therefore IMO MT should stick to its original objective in order to bring its development to a mature stage without getting sidetracked.

**Comment by Jocs** [comment]
@adrienbeau @DutchPete As you've described, Mark Text is really just a markdown editor. It  will not add the features of note taking, such as tags, metadata, etc. Mark Text provides some folder searches, open files, folders, and rename file and other features, so it should be an editor not a note taking app.

Of course, we also have the plan to launch a new application `Mark Note` focusing on the note function. Mark Note will use the save markdown editor(muya) as Mark Text use.
