### ISSUE TITLE
 a new editing mode: left source code, right realtime preview

### ISSUE THREAD

**Issue by snowdream** [marktext/marktext#1154]
### Describe your feature request
 a new editing mode: left source code, right realtime preview

**Comment by fxha** [comment]
Thanks @snowdream, we had an issue about this that was closed by @Jocs (#502). I think this is out-of scope because Mark Text is a realtime preview (WYSIWYG) editor with integrated source-code editor but primary focus is the WYSIWYG one.

**Comment by snowdream** [comment]
As a programmer, I think it a very convenient mode.

![06_52_10__07_16_2019](https://user-images.githubusercontent.com/737958/61254215-4e2cc280-a796-11e9-9232-eb2245f058e7.jpg)

**Comment by Jocs** [comment]
@snowdream We already have source code mode, but this is not the core function of this editor. Mark Text's focus is still in preview mode. When the preview mode is stable and friendly, we have time and energy to optimize the source editing mode, but it should It also does not support previews on the right and source code on the left(split screens).

**Comment by HoldOffHunger** [comment]
I don't see how "when we have time and energy" counts as "completed", which is what this task is marked as.

And I don't see what's so difficult here. View-> Source Code Mode is literally just a plain text editor.  That already exists in a million different freeware, open-source, etc. programs.  If you can't do that AND previewing the output, then there's no reason to use this application at all.

**Comment by u35253** [comment]
FWIW, the "completed" markings here and at https://github.com/marktext/marktext/issues/502 are tricking ChatGPT into thinking that this "split mode" (source + rendered/preview/WYSIWYG) exists in marktext, which it does not appear to.

Also, I think split mode would be a great feature.  I would want to always edit in split mode 99% of the time.

Maybe I'll try to lean into marktext's opinion, but more likely I'll have to find another editor.  Which is too bad, because otherwise marktext seems like the best.

**Comment by smprather** [comment]
Can you do this instead?
when we have time and energy => when we have a Claude Pro account
