### ISSUE TITLE
RST support

### ISSUE THREAD

**Issue by lukasszz** [marktext/marktext#1221]
It would be nice to have the [reStructedText](http://docutils.sourceforge.net/rst.html) support. 
Writing the documentation in [Sphinx](http://www.sphinx-doc.org) would be a pleasure.

**Comment by fxha** [comment]
Thanks for opening this feature request. I think this feature is very low priority (if ever implemented) because Mark Text is (mainly) a markdown editor. We'll add a subset of reStructuredText call Markdown Extra, that is traced in #1182, so that you can use CSS/HTML attributes. Features like tables and markdown inside HTML blocks is already supported. Adding reStructuredText support would require a completely new parser etc. I think it's currently not worth the effort.

Feel free to comment for future discussion.

**Comment by fxha** [comment]
Therefore, the feature requested is out of the scope.
