### ISSUE TITLE
无法打开手机创建或编辑过的md文件

### ISSUE THREAD

**Issue by wmbstx** [marktext/marktext#1473]
平时在手机上使用易码这个app编辑md文件，和marktext同步后发现，所有易码创建的md都无法用marktext打开，而用marktxt创建的文件，使用易码编辑后也无法再打开，都报如图所示的这个错。
![error](https://user-images.githubusercontent.com/6022880/66673742-cf133180-ec93-11e9-95f4-15a3e7dfb0d2.JPG)

**Comment by wmbstx** [comment]
附上一个示例文件

[手机测试.zip](https://github.com/marktext/marktext/files/3718990/default.zip)

**Comment by Jocs** [comment]
>附上一个示例文件

压缩文件貌似有些问题，我无法解压

**Comment by wmbstx** [comment]
> > 附上一个示例文件
> 
> 压缩文件貌似有些问题，我无法解压

换7zip重新压了个，你再试下呢

[手机测试.zip](https://github.com/marktext/marktext/files/3720255/default.zip)

**Comment by Jocs** [comment]
![屏幕快照 2019-10-12 下午2 54 14](https://user-images.githubusercontent.com/9712830/66696635-47174100-ed00-11e9-9bd5-e333c3f322ac.png)

@wmbstx 貌似，我能够打开

How strange, I can open this this file, but @wmbstx can not open it by Mark Text, @fxha do you know why?

**Comment by wmbstx** [comment]
> ![屏幕快照 2019-10-12 下午2 54 14](https://user-images.githubusercontent.com/9712830/66696635-47174100-ed00-11e9-9bd5-e333c3f322ac.png)
> 
> @wmbstx 貌似，我能够打开
> 
> How strange, I can open this this file, but @wmbstx can not open it by Mark Text, @fxha do you know why?

I forgot to say my computer is win10 and installed marktext 0.15.1

**Comment by fxha** [comment]
@wmbstx Your file is UTF-8 BOM encoded. Please change encoding via another editor to UTF-8 (without BOM) to load into Mark Text until v0.16.0.

@Jocs This is an issue with all versions <=0.15.1 due to a problem with BOM encoding but is also fixed on develop to the recent encoding changes. Node have problems to load the files when with set encoding to `utf8`, for whatever reason.
