### ISSUE TITLE
Export with theme style

### ISSUE THREAD

**Issue by AlexanderMisel** [marktext/marktext#1479]
### Describe your feature request

Export PDF with the styles defined by theme files.

### What problem does this feature solve? [optional]

The exported PDF or HTML is in the default style, which is not what we want.

### Additional context [optional]

The reason we choose a theme is not only for writing, it's also for exporting. I need an option for exporting with the theme styles. We may (future) export to academic style, as well as report style, then we will no longer need LaTeX or Microsoft Word to typeset those things.

Last year, I wrote my annual report (年终总结) with Typora, so I feel that marktext, as an open source alternative, should also be able to do so. The typesetting for that need is not so much complex, like:

- Aligning the title in the center (标题居中)
- Setting the content font to FangSong
- Add a 2em indent to each paragraph (首行缩进2字符)
- Setting the line-height (行距) and margin between paragraphs (段间距)
- Change the page margins (页边距)

If these things could be done, better with graphical interface, MarkText could be used by more people.

**Comment by Jocs** [comment]
In later versions, the export file can choose the style theme, as well as margins, line margins, paragraph margins, etc., which should be added after the 0.18.0 version.

**Comment by fxha** [comment]
Related to #349 and #354.

**Comment by L0Lock** [comment]
I wonder how it would manage dark & light themes. Especially for PDF since it's often used for printing: in that case it would not be a good idea to export a black background document.
The obvious solution would be that the user should always set a light theme when exporting for printing. But what if he wants some formating features he can only find in a dark theme (line & character spacing, styles, ...)? Could there be some form of "printable-ize theme colors" button options for that?

**Comment by fxha** [comment]
That's no problem at all, Mark Text (editor) and PDF themes are two different parts that don't interact with each other. A editor theme don't affect the PDF output or theme.

**Comment by Jocs** [comment]
I also agree the export DPF/HTML themes is different from editor theme, I don't think export `dark` theme is a good idea.(we can export GitHub theme)
