### ISSUE TITLE
Hyperlink would not render when it's in footnote.

### ISSUE THREAD

**Issue by atodniAr** [marktext/marktext#1552]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Create a footnote, say ^[1] somewhere in text, and [1]: at the end of the content.
2. Create a normal hyperlink, it would not render

**Expected behavior:**

Rendered as hyperlink.

**Actual behavior:**

Not rendering, like this:
![](https://user-images.githubusercontent.com/29804397/67377927-fc77ad80-f5b8-11e9-92a6-9d497d10f28c.png)

### Versions

- Mark Text: 0.15.1
- Operating system: macOS Catalina

Similar on my win 10 with Mark Text 0.14.0

**Comment by Jocs** [comment]
@atodniAr This will be support in the coming of version 0.16.0, and even support multiple paragraphs in footnote definition. BTY, the footnote definition syntax is `[^footnote]: abc`? and `[footnote]: abc` is reference link/image definition.

**Comment by Fastidious** [comment]
@Jocs is this on `0.16.0 RC.1`? The syntax you are referring isn't working on me on the `RC.1`. Something that quasi works is `[^footnote]` and `[^footnote]: abc` for the link to it. I say quasi work, because the rendering looks odd. See below.

<img width="665" alt="Screenshot 2019-11-12 at 13 05 36" src="https://user-images.githubusercontent.com/8352292/68697585-23d4f100-054d-11ea-98f6-abc452732beb.png">

And the source:

<img width="665" alt="Screenshot 2019-11-12 at 13 06 05" src="https://user-images.githubusercontent.com/8352292/68697613-33543a00-054d-11ea-9dff-89a3860cf502.png">

**Comment by fxha** [comment]
@Fastidious Footnotes are disabled by default, please enable Pandoc footnotes in settings under `Markdown -> Markdown extension syntax`.

**Comment by Jocs** [comment]
closed due to `footnote` is already implemented in v0.16.0. feel free to reopen it, if you have any question.

**Comment by adrienbeau** [comment]
I just tested this in 0.16.0-rc1. Footnotes work fine when the extension is enabled in the settings.
