### ISSUE TITLE
User Setting: Auto-Save New Files to Specified Directory

### ISSUE THREAD

**Issue by ecumberworth** [marktext/marktext#1604]
### Describe your feature request

As a user, I would like to start a new note, write a single line, and have the file automatically saved to a directory of my choosing. The file name should be based on the first line of text entered. For example:
```markdown
# Hello World
```
would auto save to a file:
`hello-world.md`

### What problem does this feature solve? [optional]

* Not having to always go through the process of saving files.
* Not worrying about losing data I've entered into a new note because I forgot to save.

**Comment by Jocs** [comment]
This is more like a note-taking app that automatically saves and uses the first line of text as the title. Do you use Mark Text as a note-taking software? Do you have any suggestions for the note software? Because we also have plans to make a notebook software later.

I closed this issue first due to Mark Text is a pure markdown editor, but we can continue to discuss it in this issue.

**Comment by ecumberworth** [comment]
> Do you use Mark Text as a note-taking software?

No but only because it doesn't have a note-taking workflow. I really like the markdown editor itself: simple, distraction-free, looks great.

> Do you have any suggestions for the note software?

I'd keep the same interface you have for Mark Text but just change the workflow a bit:

Have users set their Note files directory.
- Auto save new Notes to specified directory.
    - The file name should be based on the first line of text entered. 
- In the Notes List view:
    - Sort Notes by modified datetime. 
    - Display each Note's Title instead of the file name.

Bonus:
- Folders, tags, & stars.
