### ISSUE TITLE
Browser support (Chrome App)

### ISSUE THREAD

**Issue by brandonkal** [marktext/marktext#1653]
### Describe your feature request

Given that this this is already a browser app bundled with chromium, I would like to the possibility to use the editor directly in the browser. This would also be useful for ChomeOS.

### What problem does this feature solve? [optional]

This could be entirely client side with filesystem operations performed by calling an http endpoint that can easily be hosted on localhost or on a remote system.

### Additional context [optional]

[code-server](https://github.com/cdr/code-server)

**Comment by fxha** [comment]
@brandonkal Thanks for your request but this is currently out of scope of the project. Please see #772 for more information. If you need a standalone version you could try [Muya](https://github.com/marktext/muya), the core of Mark Text. Muya is currently developed in this repository and not in the linked one.

> This could be entirely client side with filesystem operations performed by calling an http endpoint that can easily be hosted on localhost or on a remote system.

Yep, your are right but we also use Electron and Node.js functions in renderer process because it's not planned to support web. There are no benefits from spending much time refactoring Mark Text to support it.

**Comment by brandonkal** [comment]
Thank you for the context on muya.

What I gather is that the intent is to make some core functions (rendering excluded) accessible to other projects but there is no plan to build or support a web client. Is that correct?

**Comment by Jocs** [comment]
> but there is no plan to build or support a web client. Is that correct?

Currently we don't have a plan to develop a web version, and we hope that other contributors/developers can use muya to develop a web version.
