### ISSUE TITLE
Add table to "turn into" menu

### ISSUE THREAD

**Issue by AndiLeni** [marktext/marktext#1657]
Hello,

it would be nice to have a menu item which inserts a table in the "turn into" menu.
This would save some time when writing :)

**Comment by Jocs** [comment]
Can you explain your feature more detail, or show some screenshot or image.

**Comment by fxha** [comment]
@Jocs I guess @AndiLeni means the line transformer `turn into` entry. If so, that's unfortunately not possible because we cannot convert other elements into a table. What's the expected behavior if you transform a line of text into a table? Should we add the existing line as header, first table cell, ...?

**Comment by AndiLeni** [comment]
@fxha You are right. This does not fit there. 
Unfortunately I don't know if there is an accurate place for this ``insert table`` feature at all

**Comment by fxha** [comment]
@AndiLeni You could use the command palette (`Ctrl+Shift+P`) from version 0.16.0 to quick insert a table or just use `Ctrl+(Shift)+T`, depending on Mark Text version.

**Comment by AndiLeni** [comment]
Okay thanks, I saw that the table can also be inserted when using the ``press @ to insert `` menu.
