### ISSUE TITLE
License GPLv3

### ISSUE THREAD

**Issue by anishmittal2020** [marktext/marktext#1761]
It is mentioned in the README.md that

> As mentioned above, Mark Text is completely free and open source and will be open source forever. We hope that all markdown lovers will contribute their own code and help develop Mark Text into a popular markdown editor.

Then, why not make the license from MIT to GPLv3? I think GPLv3 is contributor friendly.

**Comment by fxha** [comment]
Thanks for your suggestion @anishmittal2020 but that are the benefits from doing so? GPL is a restrictive license that protect your work against stealing but also comes with many downsides like integration into other applications etc.

I think personally that the GPL (+*CLA*) is not a good license and we have no benefits from it, unless you want to protect some work e.g. cloud platfrom stuff and sell it with a proprietary software. Then it would make seens to choose GPL because no one can fork it and "steal" your work.

Regarding Contributor License Agreement (CLA): If we would relicense Mark Text under GPL we (@Jocs) need a CLA to relicense Mark Text and Muya (Mark Text editor core) to another license because GPL software is not allowed in Apple's App Store.

Muya: This would also mean to relicense Muya under LGPL because Mark Text is just a wrapper around the richtext editor. I cannot really comment on this because I don't know LGPL and JS but this would make it harder to use Muya in another project because you need to dynamic link the library that is not possible in JS(?).

> I think GPLv3 is contributor friendly.

The GPL licenses are way more restrictive than the MIT license. Currently we use a permissive license and have no problems at all.

**Comment by fxha** [comment]
Closing this issue as no further information has been provided. Please feel free to reopen with more information.
