### ISSUE TITLE
Align block math formulas

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#1785]
### Question description

@Jocs  How to align block math formulas to left like:

```
Long paragraph

Short text:

$$
This should be on the left
$$

Long paragraph
```

I tested some LaTeX functions like `flalign` but they aren't supported by KaTeX (=invalid formula).

**Comment by Jocs** [comment]
@fxha Do you mean display rendered math block on the left?

**Comment by jusola** [comment]
I think you could use
```
.katex-display>.katex {
  text-align: left;
}
```
in your style .css to always align math blocks to left.

However you would need to modify the default style files and build a custom build of marktext, because custom styles don't currently work.

When custom styles are supported, this would be a solution if you want all math blocks to always be aligned to the left.

**Comment by fxha** [comment]
Closing as there seems no valid option to aligned a single math formula but not others.
