### ISSUE TITLE
Application fails when more than 5 items are added to lists

### ISSUE THREAD

**Issue by IvanFrescas** [marktext/marktext#1797]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [Create a list]
2. [Add 5 items inside the list]

**Expected behavior:**

- aaa
  - bbb
    - ccc
      - ddd
        - eee
          - fff

**Actual behavior:*

<img width="470" alt="Screen Shot 2019-12-05 at 4 36 20 PM" src="https://user-images.githubusercontent.com/16979749/70284185-7ab29c80-1780-11ea-801a-de5b1847d7ea.png">

### Versions

- Mark Text: v0.16.0-rc.2
- Operating system: macOS Catalina

**Comment by adrienbeau** [comment]
Also reproduced under Windows. Mark Text crashes as soon as the 6th level of indentation is reached.

This is a **regression**. The issue does not occur under Mark Text 0.15.1 (tested with 20 levels of indentation), but occurs in 0.16.0-rc1 and 0.16.0-rc2.

**Versions**
* Mark Text: 0.16.0-rc2
* Operating system: Windows 7

**Comment by fxha** [comment]
There is a handled native Electron exception and I don't know how to convert Chromiums dump file to CoreDumps for more details. I just did a quick search and there may be an issue with [IPC objects](https://github.com/electron/electron/issues/20334) because the passed object is too big (due to recursion limit).

```
[ERROR:validation_errors.cc(87)] Invalid message: VALIDATION_ERROR_MAX_RECURSION_DEPTH
[ERROR:render_process_host_impl.cc(4582)] Terminating render process for bad Mojo message: Received bad user message: Validation failed for ElectronBrowser RequestValidator [VALIDATION_ERROR_MAX_RECURSION_DEPTH
[ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
> The renderer process has crashed unexpected or is killed (false).
> Process terminated with exit code 3 (0x3).
```

This issue needs further investigation.

**Comment by kureus** [comment]
Some further investigation. (And some questions, I used this issue to learn about Marktext).

I can replicate the described issue on both `0.16.0-rc1` and `0.16.0-rc2` under macOS Catalina and Ubuntu 19.10, with `0.15.1` having no such problems, which confirm the regression as @adrienbeau reported. I expected to be able to open Chrome Dev Tools to get more context than the dialog box provided but this doesn't seem to be present in released versions of Marktext?

Building the Marktext repo locally and following the [debugging documentation](https://github.com/marktext/marktext/blob/develop/docs/dev/DEBUGGING.md), I found the renderer process debugging disconnects on crash, and the main process debugging only revealed a stack trace of the [crash being captured](https://github.com/marktext/marktext/blob/e78e4c6b10f1283a848c09f786b18a61336869ab/src/main/windows/editor.js#L103)

![MainProcessDebug](https://user-images.githubusercontent.com/385251/71107531-27494100-21b9-11ea-834a-1e2840253dce.png)

The console output from `yarn run dev` repeated this error with no further context.

Looking further afield for more/any context, and checking the marktext source for logging configuration, I found my way to electron-log and logs written to `~/.config/marktext-dev/logs` but they contained nothing extra, only repeating the error seen in the main process debugging.

Delving into electron docs for more debugging help I managed to get a meaningful error by setting the env variable `"ENABLE_ELECTRON_LOGGING=true"`. This led my console output to reveal the error you posted above @fxha (tho didn't affect the logs in `~/.config/marktext/logs/`)

```
[8705:1218/171908.318179:ERROR:validation_errors.cc(87)] Invalid message: VALIDATION_ERROR_MAX_RECURSION_DEPTH
[8705:1218/171908.318205:ERROR:render_process_host_impl.cc(4582)] Terminating render process for bad Mojo message: Received bad user message: Validation failed for ElectronBrowser RequestValidator [VALIDATION_ERROR_MAX_RECURSION_DEPTH 
[8705:1218/171908.318217:ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
› The renderer process has crashed unexpected or is killed (true).
```
It seems this should also create a [crash report with more detail](https://github.com/marktext/marktext/blob/3eb2f3b1819dca692508bbbbf70ff629716cd3af/src/renderer/bootstrap.js#L54), but nothing was present in `/tmp/'Marktext crashes'`. I tested the crash reporting by simulating a crash with [process.crash()](https://electronjs.org/docs/api/process#processcrash) from the console and did successfully get a crash report. At a guess as `iskilled` in my case is true, the kernel kills the process with no chance for crashpad to kick in? (On that note @fxha, the documentation on converting a minidump to a core dump is [here](https://www.chromium.org/chromium-os/packages/crash-reporting/faq#TOC-How-can-I-get-a-core-dump-from-a-minidump-for-use-by-gdb-)). Why do you believe your reproduction has `istrue` false? What OS are you on there?

Chasing the IPC error and following the [thread](https://github.com/electron/electron/issues/20334) with users experiencing issues similar to ours on electron, it seems the [switch to mojo](https://github.com/electron/electron/pull/17406) for internal IPC causes this crash due to mojo's hard 'depth' limit of 100. [0.15.1 uses electron 5.0.11](https://github.com/marktext/marktext/blob/v0.15.1/package.json#L241) and legacy IPC. [0.16.0-rc1 uses electron 7.1.1](https://github.com/marktext/marktext/blob/v0.16.0-rc.1/package.json#L116) post mojo merge. The current advice on the thread is to either hack around it by stringfying the args before emitting events on the ipc renderer, or attempting to target electron 8 which uses new 'Structured Clone-based IPC' and shouldn't suffer the problem. I built Marktext locally against Electron 8.0.0 beta 4 and the bug no longer occurrs. All unit and e2e tests pass. I also initially started looking into [IPC renderer use](https://github.com/marktext/marktext/search?q=ipcrenderer&unscoped_q=ipcrenderer) but will stop for now until there is a clear idea of how the project wants to proceed.  So it would seem to me the choice is to either 
- release 0.16 with a tested beta version of electron 8
- delay 0.16 release (if necessary) and wait for a stable release of electron 8
- move back to an electron version pre mojo merge (5.0.11. for example) for at least 0.16
- attempt to hack around the issue temporarily while we stay on this version of electron. 

For reference Electron 8 has an estimated release date of the [4th of Feb 2020](https://electronjs.org/docs/tutorial/electron-timelines). Does 0.16 have any kind of internal estimated release date? And more broadly what is the projects view on how to proceed here?

As an aside I'd like to put a PR(s) together to put some of what I learnt back into the project if you guys would be open to that?

**Comment by fxha** [comment]
Thanks @kureus for the investigation on this issue. I already through about an issue with IPC objects after first validation. 

> It seems this should also create a crash report with more detail, but nothing was present in /tmp/'Marktext crashes'. I tested the crash reporting by simulating a crash with process.crash() from the console and did successfully get a crash report.

I guess that this is not an unexpected crash, rather a controlled termination due to a precondition check, so the application is termination with an error message.

> At a guess as iskilled in my case is true, the kernel kills the process with no chance for crashpad to kick in

Yes, perhaps a little strange but the value is only `false` on Windows (with debugger attached) and on Linux always true.

> And more broadly what is the projects view on how to proceed here?

I did a quick test with the line below commented out and everything seems to work correctly and this confirms the IPC issue. I guess we finally have to solve the todo and move all needed code from main to renderer process, that was planned anyway. The IPC call is totally unnecessary and a wast of performance because we should parse the selection in renderer process and send a small object state to the main process. I guess, I can solve the issue during weekend, otherwise I'll comment here.

https://github.com/marktext/marktext/blob/09b067e3714fecbd8d18a96714f67108a643e652/src/renderer/store/editor.js#L1002

> Does 0.16 have any kind of internal estimated release date?

We had a planned release for mid November 2019 but we are both very busy these day. There is currently no planned release and we still need to triage issues that block the release of v0.16.0.

> As an aside I'd like to put a PR(s) together to put some of what I learnt back into the project if you guys would be open to that?

All contributions are welcome, whether code, help with issues or documentation.
