### ISSUE TITLE
Indented Lists

### ISSUE THREAD

**Issue by alexchut** [marktext/marktext#181]
### Description

Cursor disappears when tab is pressed to create and indented list

### Steps to reproduce

1. Create a list
2. Press tab

**Expected behavior:** Cursor moves over 4 spaces, and list is indented

**Actual behavior:** Cursor disappears

### Versions

- Mark Text: 0.10.21
- OS: WIN-64

**Comment by fxha** [comment]
Thanks for reporting this issue. I just tried list indentation with v0.10.21 and it's working perfectly fine. Do you indent the first list item because this is not supported.

The problem that you can't insert 4 spaces/tab is known and tracked in #125.

```
- a - no indentation allowed
- b<cursor + tab>
```

becomes

```
- a
    - b<cursor>
```

Or do you want to indent the entire list? e.g:

```
text
    - a
    - b
```

**Comment by fxha** [comment]
@alexchut Any updates or I'll close this issue.
