### ISSUE TITLE
Enter should insert single one break

### ISSUE THREAD

**Issue by Trismegistos84** [marktext/marktext#1855]
### Describe your feature request

Currently pressing enter insert two new line characters. This messes up *.md file source. Enter should insert single new line character or at least it should be configurable.

### What problem does this feature solve? [optional]

Messed up md source.

**Comment by ClovisGauzy** [comment]
@Trismegistos84 Use Shift+Enter ;)

**Comment by adrienbeau** [comment]
The problem is that by being a WYSIWYG editor, Mark Text hides how the paragraph is actually formatted (which you can see in source code mode or another editor).

Markdown allows a paragraph to be either a single very long line (which is what Mark Text does when you create a new paragraph) or several lines of limited length, as long as there is no blank line between them. Mark Text does not allow easily creating such a "multi-line" paragraph, the user interface for such a feature remains to be invented. (As far as I know, Typora does not allow this either.)

Markdown also allows soft breaks (two spaces at the end of a line, or a single backslash at the end of a line), but that is a different feature.

Currently, pressing Enter in Mark Text creates a new paragraph (so it adds a blank line to separate the paragraphs, that is, it inserts two new line characters as you have noted). Also, pressing Shift+Enter inserts a soft break, which is a different feature.

See also #1843 and #1849 for other issues related to this matter.

**Comment by Jocs** [comment]
>Mark Text does not allow easily creating such a "multi-line" paragraph,

@adrienbeau As @ClovisGauzy saied, you need to use `shift + enter` to create a soft break , we think create a paragraph more often than a line in a paragraph, so the `enter` key is used to create a paragraph.
