### ISSUE TITLE
keybindings.json is not respected

### ISSUE THREAD

**Issue by daeh** [marktext/marktext#1885]
### Description

`keybindings.json` does not seem to have an effect.

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Add `keybindings.json` to `~/Library/Application Support/marktext`.
2. Relaunch MarkText.app

Originally I was trying to add 
```
{
  "tabs.cycle-backward": "Cmd+Alt+Left",
  "tabs.cycle-forward": "Cmd+Alt+Right"
}
```
But after reading #1382 I thought I might need to unset the keys first. To see if I could do that, I tried this to see if `keybindings.json` had any effect, but it didn't seem to:
```
{
  "file.open-file": "",
  "tabs.cycle-forward": "Cmd+O"
}
```
I also tried using `Command+`... since I'm on MacOS but that also didn't have any effect. 

**Expected behavior:**

Keybinds to work.

**Actual behavior:**

`~/Library/Application Support/marktext/keybindings.json` file seems to have no effect.

### Versions

- Mark Text: 0.15.1
- Operating system: MacOS 10.15.2 (Catalina)

**Comment by fxha** [comment]
Thank you for reporting the issue.  Please refer to [key bindings](https://github.com/marktext/marktext/blob/develop/docs/KEYBINDINGS.md#available-modifiers) for available modifiers and keys.  If I remember correctly, the key bindings issues should be fixed in our latest release candidate and till then you have to unset the keys. Could you please try out the latest release candidate from Github releases and provide feedback?

**Comment by daeh** [comment]
Thanks. In v0.16.0-rc.2, the `keybindings.json` file works, and works without needing to unset the keys. A couple of other things I noticed:

- "Undo" does not work like I expect/want it to. Often it steps back much too far. For instance, if I type a long paragraph, delete the last two words, and then hit undo, it will remove the entire paragraph rather than undelete the last two words.

- "Redo" does not work at all.

- With some files (but not all files), as soon as I open the file it gets marked as modified and I'm asked to save it before closing it (without actually editing it at all). I'm not sure what it is about those files yet but I can look into it if that's a new issue.

- This was also true in v0.15.1, but the 'lastState' setting of 'startUpAction' doesn't actually recover the last application state (e.g. none of the files reopen). I'm not clear whether that's intended behavior or not, but it would be awesome to have Sublime-like behavior, where the application returns to basically the identical state in terms of what files were open and how they were grouped in windows.

**Comment by adrienbeau** [comment]
The undo/redo is not related to the keybindings, but to the way the feature is implemented. It will need a significant rewrite (planned for version 0.17.0) to work as most people expect. See #1321.

**Comment by fxha** [comment]
> The undo/redo is not related to the keybindings, but to the way the feature is implemented. It will need a significant rewrite (planned for version 0.17.0) to work as most people expect. See #1321.

Thanks @adrienbeau!

> With some files (but not all files), as soon as I open the file it gets marked as modified and I'm asked to save it before closing it (without actually editing it at all). I'm not sure what it is about those files yet but I can look into it if that's a new issue.

This happens because we automatically format the markdown document according CommonMark and GFM and it's (currently) not possible to keep the old format/structure.

> This was also true in v0.15.1, but the 'lastState' setting of 'startUpAction' doesn't actually recover the last application state (e.g. none of the files reopen).

`lastState` has only two options and the third is just a dummy for later (default value). Unfortunately, I don't have really time to implement a "session" to reopen the last application state (that was planned in v0.15/16). 

> Spellcheck is awesome (I only tried the system's engine). It would be amazing to be able to set the style of the underline:

I don't know whether this is possible because the underlining part is done by Chromium.
