### ISSUE TITLE
Please split build process into distinct steps

### ISSUE THREAD

**Issue by alerque** [marktext/marktext#2026]
Packaging Marktext for Arch Linux has proven to be a bit of a pain. One of the Arch Linux packaging guidelines for Electron is that copies of Electron itself should not be bundled in the package, just the source for the app should be included with a launcher that calls the system `electron` and runs the app in it. Not only does this save hundreds of MB of disk space per app installed, it also allows security updates to Electron to roll out much faster than waiting for every upstream project to update.

I've managed to make this happen for Marktext by building as per the upstream defaults, then extracting the `*.asar` and a few other resources for packaging and throwing away the Electron bits.

Both I and another packager attempted to build just the app without causing a download and build of Electron itself, but the way Marktext's build is setup is very intertwined. Nothing is separated into distinct phases or operations. Even the node package install process has pre/post hooks that mess with things outside their scope. Those are easy enough to skip, but the build step itself uses some Vue build script that in inscrutably woven in with both the app and Electron being build in one pass. Utterly inexplicably it is also trying to run `eslint` right in the middle of everything.

Please separate this mess so that linting is a distinct step (that can be skipped where not appropriate!), and such that building the app and building Electron can be done in separate stages so we can only build the app itself for packaging purposes.

**Comment by fxha** [comment]
Thanks for all the feedback and for publishing Mark Text to other distros. Repacking Electron is not supported by Electron and Mark Text but should work when you respect semantic versioning. E.g: current Electron version for v0.16.1 is `8.1.1`. That means it's fine to update to `8.1.*`, `8.x.*` requires a rebuild of native dependencies and `>=9.*:*` isn't supported. So, please make sure to include the right Electron dependency range, otherwise Mark Text is most likely to crash with weird exceptions or segfaults.

> I've managed to make this happen for Marktext by building as per the upstream defaults, then extracting the *.asar and a few other resources for packaging and throwing away the Electron bits.

You need to include all `./resources/*` files and copy both Mark Text and third-party license files. I guess there might be an issue with Hunspell dictionaries when linking against system Electron due to [this](https://github.com/marktext/marktext/blob/90fdd28afb01bfd6b0d92b4ce1241ed0966d51a2/src/main/preferences/hunspell.js#L8) function. So, please verify this and apply a patch if needed.

> Both I and another packager attempted to build just the app without causing a download and build of Electron itself
> [...]
> and such that building the app and building Electron can be done in separate stages so we can only build the app itself for packaging purposes.

I'm not a JS developer but we're using `electron-builder` to build/download the binaries and create the resources files such as `app.asar`. As far as I know, there is not way to build these files without downloading Electron. You should take a look at the official [documentation](https://www.electron.build/) but the library doesn't seem to be active maintained.

For example `build:bin`: In this step, we just bundle both main and renderer process code and launch `electron-builder` to pack the application.

```
build:bin
  -> build script (webpack)
      -  bundle JS source code into two files for main and renderer process
    -> electron-builder
        -  pack asar file
        -  compile native dependencies
        -  some mirror build steps such as coping files
        -  download Electron (or use from cache)
        -  put all together
```

> Please separate this mess so that linting is a distinct step (that can be skipped where not appropriate!)

That's true but the main idea behind this is to recognize syntax errors that would cause runtime crashes. I think it's needed for JS but not for other languages that are compiled. `eslint` is also a dependencies that is automatically downloaded and you just need to ensure that all [prerequisites](https://github.com/marktext/marktext/blob/develop/docs/dev/BUILD.md#prerequisites) are installed.

As you can see, we depend on `electron-builder` to create all resource files or, in other words, to create the application. Feel free to open a PR if you find a way to only output the resource files without Electron. I think it's not a big deal to download Electron on a worker to get the distro specific package and distribute the created package. We would be happy to accept a PR for this but I don't think it's possible with the current build system and with our available time. First, we will need an active maintainer and then focus on the opened issues and bugs.

The most impotent part is to link against the right version of Electron. For v0.16.1, you need to link against "`electron-6`" and hope that the same node ABI is used or otherwise this would lead to a segault.

**Comment by alerque** [comment]
I think you missed the point. I'm familiar with packaging Electron apps for Arch Linux, I handle packaging for quite a few of them. Electron-builder is not my favorite, but it can be made to work. The problem is you haven't exposed any way to call it directly. The best I can do is call a build script which does a web pack and then calls out to electron-builder on its own ... with a bunch of options I don't want. Like "downloading Electron" and "put it all together".

The request here is to split this monolithic behemoth build script up into distinct phases. You can still have a `build:bin` or whatever that calls all the phases sequentially, but for packaging purposes we need to pick and choose. I'll need the webpack, then the "pack asar", and a "compile native deps" (against a version of electron that I specify in cli arguments, and that's it. In other words I need the webpack bit to run and just do it's thing without jumping the gun and firing off a bunch of things I don't want. I can call `elcetron-builder` with by on arguments to make the rest happen in a way that will build using the system provided Electron.

**Comment by fxha** [comment]
> Electron-builder is not my favorite, but it can be made to work.

Could you please give an example how to only build `asar` archives with `electron-builder`?

> I'll need the webpack, then the "pack asar", and a "compile native deps" 

I don't know how to do this with `electron-builder` because the builder does everything in one step, as written above. You can run `yarn pack` to get all bundled files inside the `dist` directory but without needed dependencies. Then you need to figure out, how to pack the files and dependencies as `asar` archive. Native binaries are compiled by yarn (install) (or `yarn rebuild`) in the `node_modules/` directory but should be put outside the `asar` archive due to various problems with execute permissions.

I hope that this information helps, otherwise you need to open an issue on `electron-builder` to get a standalone `asar` archive. Please add a version suffix like `v0.16.1 for Arch`, so we can distinguish the repacked version in issues.

**Comment by alerque** [comment]
Here are some extracted bits from another Electron app I package. You can ignore than this project uses `yarn` instead of `npm`, this is just to give you an idea of how the build process can be done on a project that doesn't mash the entire build sequence together in one stream:

```bash
local _electron="$(electron --version | sed 's/^v//')"
npx electron-rebuild --version="$_electron"
# {skipping some pruning stuff to get rin of un-needed bits}
npx electron-packager ./ "$pkgname" \
    --electron-version="$_electron" \
    --overwrite \
    --asar \
    --platform=linux \
    --arch=x64
```

The result is only rebuilding some of the project's native modules (node-gyp stuff) against the system's version of Electron and then generating an asar file that can be shipped as the package along with a wrapper script to call it using the system Electron.

I'd be happy to set the version string to identify the system. Where do I do that properly? Also it might be a good idea to report the Electron version separately from the app's version.

**Comment by fxha** [comment]
Thanks for your reply but this example using `electron-packager` and not `electron-builder`, as we do. I also don't see the point of moving to another builder because `electron-builder` is already configured and also manages CI uploads and automatically updates etc. For the time being, we keep `electron-builder` but I'll keep this issue open for other suggestions. Maybe you can open an issue directly on `electron-builder` to only build the `asar` archive. It would be the simplest solution without changing almost everything or you could also try to run `electron-packager` on Mark Text and `dist/` output from webpack.

> I'd be happy to set the version string to identify the system. Where do I do that properly?

It's currently not implemented but we could add an environment variable to specify an additional string.

**Comment by alerque** [comment]
I've found that `electron-builder` is perfectly capable of building against a system Electron package. You can either set the path to the Electron distribution to use in the config file or pass it command line args. I can do that in packaging modifications just fine, but `eslint` still screws things up. The build pipeline _before_ getting to `electron-builder` expects to find Electron stuff and do ... I have no idea what with it. That's the part I can't get past.

**Comment by fxha** [comment]
Have you tried to set `failOnError` to false in both webpack [main](https://github.com/marktext/marktext/blob/90fdd28afb01bfd6b0d92b4ce1241ed0966d51a2/.electron-vue/webpack.main.config.js#L30) and renderer?

**Comment by fxha** [comment]
I'm closing this issue as there are no changes planned in near future and you can workaround this.
