### ISSUE TITLE
Request: Create an AUR package for marktext

### ISSUE THREAD

**Issue by dessalines** [marktext/marktext#212]

**Comment by fxha** [comment]
Same as in #65. We don't support debian, RHEL and arch as a standalone package, but we provide a AppImage which can run on all distros. I would not recommend to use snappy because I'll replace it later with flatpak - hopefully before v1.0 is released - and there are some problems with not debian-distros. So don't expect snappy to run on arch. See [here](https://github.com/marktext/marktext/blob/master/doc/linux.md) for linux instructions.
