### ISSUE TITLE
Electron 9

### ISSUE THREAD

**Issue by fxha** [marktext/marktext#2128]
Plan of updating Electron to version 9:

- [x] Sending non-JS objects over IPC now throws [an exception](https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception). We need to verify all IPC calls.
- [x] `shell.openItem` is now `shell.openPath`
- [x] Change native modules to NAPI (#1928). We could temporarily set `app.allowRendererProcessReuse` to `false` until Electron 11.

**Comment by Nesaijn** [comment]
I would be happy to see this implemented, since on Arch based distros there is a problem when installing it from AUR. The AppImage is still usable though.
See comments from "monoid" on 2020-06-02 to the most recent:
https://aur.archlinux.org/packages/marktext/

**Comment by alerque** [comment]
@Nesaijn You did notice that the AUR package has been updated more recently than any of the comments (including my own) mentioning the issues right? It compiles and works fine right now — all be it with the somewhat less than idea solution of _downgrading_ to the latest Electron 7 package that's in the Arch [community] repo. Arch currently has 7 or 9 but no 8 in official packages (since no official packages require 8).

**Comment by Nesaijn** [comment]
Oh, did not notice. Thank you!
