### ISSUE TITLE
isMaximized: true issue

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#217]
### Description
When `isMaximized` is set to `true`, (window-state.json) I can't open any files. It will simply open a new untitled file whenever I attempt to open one.

### Steps to reproduce

1. Go to `%appdata%/marktext` and open `window-state.json`
2. Change `"isMaximized":false` to `"isMaximized":true`
3. Open a file

Alternative steps:
1. Open Marktext
2. Maximize the window
3. Close Marktext
4. Open it again and attempt to open a document

**Expected behavior:** The correct file gets opened

**Actual behavior:** A new untitled file gets opened

### Versions

- Mark Text: v0.10.21
- OS: Windows 10

**Comment by fxha** [comment]
I can confirm the issue on Linux and Windows.

@Jocs Can you reproduce the issue on macOS?

**Comment by Jocs** [comment]
@fxha I can’t understand this issue at all, I think it’s not existed on Mac.

**Comment by Jocs** [comment]
@fxha is it a problem on linux and windows?

**Comment by Jocs** [comment]
I’ll try it latter, weather it is existed on MacOs?

**Comment by Jocs** [comment]
@fxha I have tested it on MacOs, it also has the problem!

**Comment by fxha** [comment]
As far as I can say, it's a electron bug because `ready-to-show` event is not triggered if app is started maximized or in full-screen mode. Let me look into it this evening or tomorrow and then report the issue to the electron team if it's a electron bug. But maybe there are some conflicts with `electron-window-state`.

https://github.com/marktext/marktext/blob/9882dbe59c9fe1edd06d8d0fec113aa631dc6f83/src/main/createWindow.js#L71

At the moment I created only few log outputs around `createWindow(...)` and `ready-to-show` get not triggered. So we should check other possibilities.

**Comment by Jocs** [comment]
OK, maybe it's a bug of electron 2.0.0-beta.7, but I am not sure.
