### ISSUE TITLE
forking Typora

### ISSUE THREAD

**Issue by lewisl** [marktext/marktext#2291]
### Question description

Did you fork Typora?   Seems like it.

Why would you want to hurt Abner's chance to earn a living?

Indie developers are as honorable as OSS developers. The right to earn a living is ethical.

**Comment by brainchild0** [comment]
Typora is a closed-source, commercial product. Mark Text is an open-source, non-commercial project, begun by Ran Luo, created from open-source components, and supported by volunteers.

What you have suggested would be theft of property. It is probably a bad idea, and certainly not polite, to throw suggestions that someone is a thief before you have any actual information on the subject.

**Comment by lewisl** [comment]
Thanks for the correction.  I had received information that Mark Text was a fork, but if there was no code available to fork then impossible.

I stand corrected and apologize to you.

From your standpoint, as OSS or not, paychecks are ethical and legitimate and some projects can provide lead contributors with a paycheck and some cannot. Hope yours can.

**Comment by brainchild0** [comment]
If you have an objection to open-source software, then you should find a place to discuss it generally, separate from any project. But I also suggest that you educate yourself first, because you seem to have some inaccurate ideas. I think that people will be more interested in talking to you if you ask questions about what you might not know, instead of saying the things that you seem to think right now.

This is the wrong place for that discussion. If volunteers come someplace  to help after a natural disaster, would you thank them, or complain that someone should be paid to do the work instead? You may have your ideas, but you can still be polite.

**Comment by YalandHong** [comment]
@lewisl 
> Did you fork Typora? Seems like it.

Forking Typora is impossible, since it's commercial software. But I agree that MarkText is *similar* to Typora to some extent. This is probably because the two products are both powered by some well-known front end technologies (such as JavaScript, CSS and Electron). You can find a list of third-party libraries on the website of Typora.

> Why would you want to hurt Abner's chance to earn a living?

What do you mean "hurt"? It is users that decide which is better and which to support. Besides, I don't think Abner has lost the revenue. Typora is still a famous and more developed product acknowledged by its users.


By the way, please close this issue. The developers need to save their time for other issues in order to improve the product.

Thanks!

**Comment by brainchild0** [comment]
There are many problems with the ideas expressed by the author of this issue, including that Typora depends on Electron, which is open source, and which depends on Chromium, which is open source. Private industry benefits tremendously from open-source software, and in fact, most commercial software projects use open-source tools and components.

The author should  read about OSS before making conclusions, and yes, also should close this issue.

**Comment by berserkwarwolf** [comment]
This issue should be closed.
