### ISSUE TITLE
I think you can add catalogs

### ISSUE THREAD

**Issue by Anditty** [marktext/marktext#2539]
In typora, we can use [toc] to generate a contents conveniently, I hope in mark text, you can add this~
if there is a way to generate catalogs but I don't know , please tell me that~ thx!

**Comment by Anditty** [comment]
And  I want to use relative path to insert image, through which I can open it in another computer convenient, so if there is a function that I can use relative path automatically when I insert a picture?

**Comment by YalandHong** [comment]
> In typora, we can use [toc] to generate a contents conveniently, I hope in mark text, you can add this~ if there is a way to generate catalogs but I don't know , please tell me that~ thx!

For generating TOC in current position, it's a dup of #1877. For generating TOC at the top of the document, it's a dup of #80.

MarkText plan to implement TOC generation only in the exported file (https://github.com/marktext/marktext/issues/685#issuecomment-463622825). marked as low priority since it's not standard GitHub Flavored Markdown syntax.

关于自动生成目录的功能，类似的issue已经有人提过了（#1877 #80 ）。MarkText打算首先实现 (https://github.com/marktext/marktext/issues/685#issuecomment-463622825) 在导出的HTML/PDF中生成目录。对于你说的Typora的TOC会自动随文档内容改变的功能，由于不是标准的GitHub风格的Markdown语法，暂时不优先考虑。

----

> And I want to use relative path to insert image, through which I can open it in another computer convenient, so if there is a function that I can use relative path automatically when I insert a picture?

Dup of #2560. Please report your problem and discuss there.

关于图片相对路径的问题，请到 #2560 中讨论
