### ISSUE TITLE
Add support for markdown links 

### ISSUE THREAD

**Issue by mrusso99** [marktext/marktext#2545]

**Comment by dxps** [comment]
What do you actually mean?

Asking since I see that it supports it:
- this is how it looks when you have the cursor on the paragraph
  ![image](https://user-images.githubusercontent.com/14140226/116197325-4bb61580-a73d-11eb-9d06-dd29aebdc650.png)
- and this is how it looks otherwise:
  ![image](https://user-images.githubusercontent.com/14140226/116197430-6d170180-a73d-11eb-83cf-eda4b8859c16.png)

**Comment by Duckbilled** [comment]
Does it support in text linking too? I am switching from Typora where this is possible, but does not automatically seems to work in Mark Text.

For example: 
`<a Anker="Anker">Anker</a>`
`[Text](#Anker)`

**Comment by dxps** [comment]
My case also (evaluating it as an alternative to Typora, since I can't stand anymore the missing tabs in Linux).
Have you tried?

It looks that it's working:
![image](https://user-images.githubusercontent.com/14140226/116270750-0a972300-a788-11eb-969f-e64a4c982afe.png)

**Comment by Duckbilled** [comment]
When I click the text, nothing happens (expecting it to scroll down/up to the anker), so I think it is not.
