### ISSUE TITLE
Typing underscore ("_") adds additional underscore after cursor

### ISSUE THREAD

**Issue by markmillerdev** [marktext/marktext#2566]
### Description

I searched existing issues but could not find anything related.  This issue was observed in  v0.16.2.  When I am in the non-Source Code Mode (i.e, regular mode) and type a string that contains an underscore, another underscore appears ahead of the cursor. As I continue to type, the additional underscore gets pushed ahead, such that it will appear at the end of the sentence I am typing.

- [ ] Can you reproduce the issue? 
- [ X] Yes

### Steps to reproduce

Type a word that contains an underscore, such as 'my_variable'.  When the underscore is typed, you will see another underscore ahead of the cursor, and will push ahead as typing continues.

As example, if I typed 'This is my_variable' it would end up like 'This is my_variable_'

**Expected behavior:**

There should be no additional underscore symbol.

**Actual behavior:**

Underscore is added to typing

**Link to an example: [optional]**

### Versions

- Mark Text version: v0.16.2
- Operating system: OSX 11.3

**Comment by FranzMari** [comment]
Hi,
This happens because, in the markdown syntax, the underscore is used to make text italic (i.e. \_text\_ becomes _text_, as you can see in this comments editor).
The same happens if you type, for instance, an *

I understand this is not funny when you have to write many variables containing and underscore: you can disable the automatic markdown syntax completion in the editor settings in order to avoid the behaviour.

IMHO this isn't a bug

**Comment by e-pet** [comment]
I just came to this forum to say that I find myself fighting the autocompletion behavior *all the time*. I'm generally fine with autocompletion (I'm used to working with IDEs etc.), but for some reason, the particular behavior implemented in Mark Text is extremely unintuitive for me. I think part of the problem is that it completely breaks any manual marking up that you want to do. So even if you enjoy the autocompletion in general but every once in a while want to edit things manually, this gets in the way big time. I believe that's different from autocompletion features in other editors, which are much more unobtrusive and essentially leave the user both the option to use it or not to use it (without being actively hindered by it).

Just as one example that I find very annoying: I have written a word and decide that I want to mark it up. So I type "*" after the word (intending next to go back and type another star before the word). The star is automatically duplicated so that I end up with "word*|*" (cursor in the middle). I realize that I now have one star too much, so I try to delete one, but no matter whether I use delete or backspace *both* stars disappear again. So it seems like there is simply *no way* to enter a single star, and thereby do the mark-up manually! I've been fighting with this a lot. (After a while I figured out that there's a workaround: you can move the cursor after the second star and then press backspace. That way, one star remains. But... well... judge for yourself whether that counts as intuitive behavior...)

**Comment by martinwittmann** [comment]
I just checked how Typora handles this. They do autocomplete markdown syntax but only if the character before the cursor is non-alphanumeric.
This way users wouldn't need to completely disable syntax completion and yet it would not get in their way.

Personally, I can see this being a major issue for many users since typing underscores in random text is not that uncommon, I guess.

**Comment by martinwittmann** [comment]
I created #2607 with a possible solution, which only completes markdown syntax if the previous character is non-alphanumeric.

**Comment by noahbliss** [comment]
I'm opening a similar issue with this as a heads-up. Specifically that markdown autocomplete should be disabled inside of code blocks.
