### ISSUE TITLE
Really slow startup on Win10

### ISSUE THREAD

**Issue by NoahELE** [marktext/marktext#2638]
### Question description
I wonder whether it is a normal case that it takes about 10-20 seconds to open the app. The time is counted from the loading sign shows to the edit box is shown.

**Comment by kmahyyg** [comment]
Same problem here. Really slow after I double-clicked the exe file.

**Comment by loyukfai** [comment]
Having tried Typora and iA Writer, MT is strangely slow on launch and opening preferences.

**Comment by cmilham** [comment]
Same issue here on Windows 10. Very slow to start up. It is a particular issue because I am using it as the external editor for Joplin, and it takes over 10 seconds to start even if run immediately before, closed down, then opened again. Some system info below. Is there any other testing/info I can provide?

System: 
Processor	Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz   2.49 GHz
Installed RAM	12.0 GB (11.7 GB usable)
Edition	Windows 10 Pro
Version	21H1
OS build	19043.1348
SATA SSD
