### ISSUE TITLE
MarkText doesnt open anything

### ISSUE THREAD

**Issue by IntelliNik** [marktext/marktext#265]
### Description

Hello everyone,
firstly i want to say that you´ve made a very useful and beautyful tool to work with markdown. Thank you for that! I all worked finely until now MarkText now doesnt open any file at all. Either if I open the file via the explorer or if i open a file via MarkText directly. I´ve installed MarkText again, but nothing changed.

### Steps to reproduce
I dont know how to reproduce this, it was just there!

**Expected behavior:** [What you expected to happen]
open a file
**Actual behavior:** [What actually happened]
doesnt open a file
**Link to an example:** [If you're reporting a bug that's not reproducible, or it's hard to description, please paste a screenshot of reproducing this issue, gif format is appropriate]

### Versions

- Mark Text: 0.10.21
- OS: Windows 10 x64

**Comment by IntelliNik** [comment]
Hey @fxha,

thanks for the quick response, in my error log was just this:

2.5.2018, 20:43:18 [ERROR] Cannot save file without path.

But when i deleted the "%appdata%\marktext-folder" it solved the issue. Thank you very much!

Greetings,

IntelliNik

**Comment by L-curiosity** [comment]
I encountered this problem because I accidentally deleted all the configuration files of typora in the system directory, which caused all my md format documents to not be displayed normally through Typora.
And I solved this problem by reinstalling it.

**Comment by its-mohitkumar-7** [comment]
I’m not sure whether my issue is related to #265, but I encountered a similar problem on Debian, so this work around may help someone experiencing the same issue.

When opening a selected `foo.md` file directly from the file manager, MarkText would open a blank window instead of the selected file. The same file opened correctly when launching MarkText from the terminal.

I installed MarkText from the `.deb` release asset, and the file was located under `$HOME`.

I fixed the issue by changing the `%U` field code to `%F` in `/usr/share/applications/marktext.desktop`:

```
Exec=/opt/marktext/marktext %U
```
to:
```
Exec=/opt/marktext/marktext %F
```

After restarting MarkText, opening `.md` files directly from the file manager worked as expected.


**Environment:**

- MarkText: v0.19.1
- Node.js: 24.15.0
- Electron: 42.1.0
- Chromium: 148.0.7778.97
- Debian: 13.6
