### ISSUE TITLE
Hope to launch Chinese|希望推出中文

### ISSUE THREAD

**Issue by 123shiyue** [marktext/marktext#2680]
没有中文对中国玩家来说,使用难道较大,希望开发者**推出中文**,谢谢!
Without Chinese, it is difficult for Chinese players to use.I hope that developers will launch **Chinese**, thanks!

**Comment by Suomm** [comment]
good！

**Comment by LaoshuBaby** [comment]
在Typora之后，许多不同国家反对Typora商业化的用户将涌向Marktext。
拥有原生的多语言支持而非要求用户对着翻译软件来使用Marktext，可以让Marktext变得更加易用。

**Comment by LaoshuBaby** [comment]
虽然#138 已经不止一次提到说这些是Duplicate
但我依然要对这种“重复就关闭”的社区模式说不
如果一个问题反复被提及，那开发者最好是去真的处理这个问题，而不是仅仅关闭一个Issue
因为Issue会被一次又一次的再创建，直到这个问题真的被处理得当。

**Comment by itibbers** [comment]
> 虽然#138 已经不止一次提到说这些是Duplicate 但我依然要对这种“重复就关闭”的社区模式说不 如果一个问题反复被提及，那开发者最好是去真的处理这个问题，而不是仅仅关闭一个Issue 因为Issue会被一次又一次的再创建，直到这个问题真的被处理得当。

开发者肯定在处理了啊，不管未来支不支持。

提交重复的 issue 本来就会增加工作量，标记 duplicate 不也是为了方便管理嘛。

另外提 issue 之前，是不是应该先看下有没有相同的问题，查下进度。

你要有能力就提 pr。

**Comment by LaoshuBaby** [comment]
> 你要有能力就提 pr。

好啊，现学现卖喽

**Comment by wang1212** [comment]
首先应该询问项目维护者，项目是否有支持国际化的计划？自己是否可以做出贡献？而不是一上来就要求 XXX。

**Comment by Jocs** [comment]
This is the [reason](https://github.com/marktext/marktext/issues/138#issuecomment-981650531) why the internationalization is delayed. I still hope that you will discuss it on the previous [issue]( https://github.com/marktext/marktext/issues/138). We will also look at your needs. This issue is closed first.
