### ISSUE TITLE
Clicking on Table of Contents items does not jump to section

### ISSUE THREAD

**Issue by bardo84** [marktext/marktext#2699]
As the title says.

What a nice app!

**Comment by YalandHong** [comment]
More info is needed. It may be a dup of #2261, which is also a dup of #1775

This issue is probably caused by fractional zooming in high DPI. (see this [comment](https://github.com/marktext/marktext/issues/2261#issuecomment-955628957))

The problem also seems to appear when you search the document, i.e. using Ctrl+F.

Please close this issue if it helps. Thanks!

----

你提供的信息太少了，最好有截图或者更详细的描述。

不过这个问题可能有人提过了（#2261 #1916 #1775）。MarkText目前还不能很好地支持某些高分辨率屏幕的缩放（比如Windows下1080P常用的125%缩放比），在涉及跳转的时候（比如点击左侧目录跳转、Ctrl+F搜索文档）可能会有问题。

如果你遇到的是这个问题，请在 #1775 中讨论，然后关闭这个issue。谢谢！

**Comment by bardo84** [comment]
Workaround with High DPI Scaling override to System fixed it - thx!

Would recommend adding a Known bugs/workarounds to web site or GitHub.
