### ISSUE TITLE
Unable to jump to the corresponding location by clicking the outline entry

### ISSUE THREAD

**Issue by luwanglin** [marktext/marktext#2729]
### Description

Unable to jump to the corresponding location by clicking the outline entry

### Steps to reproduce

![image](https://user-images.githubusercontent.com/34809270/144564645-2f1bb4d2-fd6b-46cf-804e-12a8e094bd58.png)

**Expected behavior:**

**Actual behavior:**

**Link to an example: [optional]**

### Versions

- Mark Text version: v0.16.3
- Operating system: Windows10 21H1

**Comment by YalandHong** [comment]
Dup of #1775

This issue is probably caused by fractional zooming in high DPI. ([comment](https://github.com/marktext/marktext/issues/2261#issuecomment-955628957))

The problem also seems to appear when you search the document, i.e. using Ctrl+F.

*Please close this issue if it helps*. There're way too many duplicate issues in this repo. Thanks!

**Comment by luwanglin** [comment]
> 

thanks your replay.
