### ISSUE TITLE
【提问】生成的目录点击无法跳转，有什么解决方法吗？？

### ISSUE THREAD

**Issue by Janer63** [marktext/marktext#2736]
生成的目录点击无法跳转，有什么解决方法吗？？

**Comment by YalandHong** [comment]
Possible dup of #1775. Please check if there's any workaround there.

In order to reduce duplications, please close this issue and report your problems there. Thanks!

----

这个问题已经有人提过了（#1775）

MarkText目前还不能很好地支持某些高分辨率屏幕的缩放（比如Windows下1080P常用的125%缩放比），在涉及跳转的时候（比如点击左侧目录跳转、Ctrl+F搜索文档）可能会有问题。

目前的临时解决方法是修改MarkText缩放比或者系统缩放比：
Windows：https://github.com/marktext/marktext/issues/1775#issuecomment-771994238
Ubuntu：https://github.com/marktext/marktext/issues/2261#issuecomment-955628957

如果你遇到的是这个问题，请在 #1775 中讨论，然后关闭这个issue。谢谢！
