### ISSUE TITLE
A markdown file can't read by Marktext, but Typora is ok!

### ISSUE THREAD

**Issue by kewtgh** [marktext/marktext#2779]
### Question description
I have a markdown file with learning  notes. But it can be opened by Typora and can't be opened by Marktext.

Checked and don't know why.

[[Learn] Hello World!.md](https://github.com/marktext/marktext/files/7769607/Learn.Hello.World.md)
![opened by typora](https://user-images.githubusercontent.com/55637096/147249110-bb64d921-e51e-40ec-b9b8-7e420ce46b4d.png)
![opened by marktext](https://user-images.githubusercontent.com/55637096/147249117-bd401492-dc22-401f-9bf2-30b5814da61c.png)

**Comment by bolshoytoster** [comment]
It opens fine for me, if possible could you try running marktext from the terminal/command line with `--safe`. If that doesn't work you could try reinstalling it.

**Comment by kewtgh** [comment]
> It opens fine for me, if possible could you try running marktext from the terminal/command line with `--safe`. If that doesn't work you could try reinstalling it.

Thanks.
I've tried several methods, restore the preferences to default, open the file in Linux version, safely open. It didn't work.
Only one that delete all user files and reinstall can solve the problem.
But still don't know why. Because my Linux version's preferences are all default setting, except open default folder.

Anyway，thanks for your help.

**Comment by kewtgh** [comment]
> It opens fine for me, if possible could you try running marktext from the terminal/command line with `--safe`. If that doesn't work you could try reinstalling it.

Thanks.
I've tried several methods, restore the preferences to default, open the file in Linux version, safely open. It didn't work.
Only one that delete all user files and reinstall can solve the problem.
But still don't know why. Because my Linux version's preferences are all default setting, except open default folder.

Anyway，thanks for your help.

**Comment by kewtgh** [comment]
I tried that to close the function of open default folder. It worked.
It seems that to open default folder has a bug.

**Comment by bolshoytoster** [comment]
@kewtgh I've managed to recreate this, I'll see if I can fix it.

**Comment by bolshoytoster** [comment]
This also occurs if `Open files in new window` is set enabled.

**Comment by kewtgh** [comment]
> This also occurs if `Open files in new window` is set enabled.
> 
> It also occurs if you try to open a file from the command line.
> 
> So it's something to do with opening a file/directory in the window initialization.
> 
> It also doesn't happen if the file/directory you try to open doesn't exist, this could help track it down.

Thanks.

**Comment by bolshoytoster** [comment]
I've fixed this, I'm opening a pull request now.

**Comment by fxha** [comment]
Mark Text is unable to load the file because our markdown parser for footnotes has a bug that causes a DoS. A DoS occurs when parsing footnotes without new line(s) or spaces between tag and content. The issue is located here:

https://github.com/marktext/marktext/blob/4c0d960bccc9ef62ca68cf23e127f307bd49e3f2/src/muya/lib/parser/marked/blockRules.js#L40

The above regex is not restricted enough and allows to parse strings like `[^1]:foo bar` where `[^1]:foo` is the footnote tag and `bar` the text.

https://github.com/marktext/marktext/blob/4c0d960bccc9ef62ca68cf23e127f307bd49e3f2/src/muya/lib/parser/marked/lexer.js#L198

Here, the remaining content should be parsed but the prefix isn't removed due to the regex mismatch and we got a endless loop.

**Stack Trace:**

```
vue.esm.js:1906 RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Lexer.token (lexer.js:73)
    at Lexer.token (lexer.js:216)
    at Lexer.token (lexer.js:216)
    at Lexer.token (lexer.js:216)
    at Lexer.token (lexer.js:216)
    at Lexer.token (lexer.js:216)
    at Lexer.token (lexer.js:216)
    at Lexer.token (lexer.js:216)
    at Lexer.token (lexer.js:216)

Lexer := src/muya/lib/parser/marked/lexer.js
```

**Minimal Example**

```
foo[^1]

[^1]:foo
```

```
foo[^1]

[^1]:foo bar baz
```

**Steps to resolve:**

- Read Pandocs footnote specification again to answer remaining questions about the allowed syntax
- Restrict the RegEx in blockRules.js to explicitly match `[^` text `]:`, where `text` is defined by specification
- Fix inner RegEx to remove the prefix in lexer.js

Note the following footnotes are allow (maybe more):

- `[^text]:<one or more spaces/tabs><markdown>`
- `[^text]:\n<markdown>`

/cc @Jocs

**Comment by YalandHong** [comment]
Possibly related to #2459?
