### ISSUE TITLE
macOS x64 binary contains arm64 native keytar library

### ISSUE THREAD

**Issue by Duckbilled** [marktext/marktext#2953]
### Steps to reproduce

1. Download MarkText (either x64 .dmg or .zip)
2. open and allow running the application in system preferences
3. you will receive an error with the message as seen in the screenshots (couldn't copy the text)

<img width="261" alt="Screenshot 2022-01-29 at 20 52 24" src="https://user-images.githubusercontent.com/52334713/151675591-b16faa58-90f1-46b0-a381-bfe5370ccf16.png">

<img width="257" alt="Screenshot 2022-01-29 at 20 53 04" src="https://user-images.githubusercontent.com/52334713/151675594-5a531825-a976-4d7b-a587-bb3d14304c22.png">

<img width="258" alt="Screenshot 2022-01-29 at 20 53 13" src="https://user-images.githubusercontent.com/52334713/151675596-e4eb7c0a-14a3-48be-8d8f-c5360ea9b158.png">

### Versions

- MarkText: 0.17.0-rc.1 
- Operating system: MacOS Monterey 12.2

**Comment by fxha** [comment]
Issue: macOS x64 binary contains arm64 native library (keytar).

@Jocs I think I know the problem here. Could you try to `yarn remove keytar` and `yarn add keytar` to force update all dependencies and build the binaries with `node_modules/.bin/electron-builder build --mac --publish never`. This should hopefully download the right prebuilt library, otherwise we would have to disable prebuilt stuff.

**Comment by Jocs** [comment]
@fxha I build on macOS with command `yarn run release:mac --publish never` after `yarn remove keytar` and `yarn add keytar`, and it build correctly.

**Comment by Jocs** [comment]
Is it because node_modules caches keytar? Can we disable keytar caching?

**Comment by fxha** [comment]
> Is it because CI caches keytar? Can we disable keytar caching?

I guess it's because the dependencies from `keytar` were not correctly updated and the CI worker had to use the version from `yarn.lock` that may be outdated or bugged. keytar is the only native dependency that download pre-built binaries, but downloaded arm64 for x64 target. I'll create a PR where we regenerate `electron-builder` too.
