### ISSUE TITLE
No syntax highlighting in C++ code block until file is saved and reopened

### ISSUE THREAD

**Issue by v1nh1shungry** [marktext/marktext#2993]
### Description

No syntax highlighting in C++ code block until the markdown file is saved and reopened.

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. Open MarkText without opening any files and ensure source code mode is off.
2. Create a C++ code block (three backticks, cpp, newline and three backticks).
3. Type some C++ codes.

**Expected behavior:**

The syntaxes are highlighted.

**Actual behavior:**

No syntaxes are highlighted. However, syntax highlighting in code blocks of other languages are normal. And after I saved the markdown file, close the file, and open the file, the syntax highlighting in C++ code block becomes normal.

**Link to an example: [optional]**

![image](https://user-images.githubusercontent.com/98312435/153010098-9909c469-15f1-4c46-9a4a-70bc765826f0.png)

### Versions

- MarkText version: v0.17.0-rc.1
- Operating system: Windows 10 version 21H2

**Comment by Jocs** [comment]
I can't reproduce the issue, can you record a video?

**Comment by v1nh1shungry** [comment]
After I opened the issue, I uninstalled the software. And I reinstalled MartText just now and I find that the syntax highlighting just works perfectly! Maybe there was something wrong with my last installation. Anyway, thanks for replying and so sorry for wasting your time.

**Comment by tiger-flying** [comment]
I can reproduce this after first installation. Firstly the code was tagged as "c++"(was written in Typora) rather than "cpp", and there's no syntax highlight.  
After change the languange type from "c++" to "cpp", no syntax highlight as well. 
Then I save the change and exit MarkText and reopen later, the syntax highlight works now. 

I'm using v0.17.0 in macos 12.3 Beta (21E5222a). The package(marktext-x64.dmg) was downloaded from this github repository.

**Comment by chenxli** [comment]
My CPP code block can't be highlighted, but C is OK.

**Comment by Jocs** [comment]
Thanks for the detailed report (and to everyone who confirmed it on 0.17.x). This was a bug in the old editor engine, where a language whose grammar has a dependency — C++ (`cpp`) depends on `c` — wasn't re-highlighted after its grammar finished loading asynchronously, so it only appeared after save+reopen.

The editor engine has since been rewritten. In the current code the code block re-renders itself once the language (and its dependencies) finish loading, so `cpp` highlights live as you type without any save/reopen. I'm closing this as resolved by the engine migration, but please reopen with a repro on a current build if you still hit it.
