### ISSUE TITLE
Deleting a new line can duplicate stuff

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#301]
### Description

Deleting a new line can duplicate stuff can duplicate a `code block`

### Steps to reproduce

1. Type
```
hello
`how are you?`
```
2. Move the cursor after `hello`
3. Hit the delete key (to delete the new line)
4. `how are you` will get duplicated

**Expected behavior:**
![image](https://user-images.githubusercontent.com/10220080/40537349-fb77ba6a-600e-11e8-9fb9-d0e26436a93f.png)

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/10220080/40537317-e71b8d44-600e-11e8-8490-9ef5dbb3ad75.png)

### Versions

- Mark Text: v 0.10.21
- OS: Windows 10

**Comment by Jocs** [comment]
@stefnotch 
>Hit the delete key (to delete the new line)

If the cursor is after `hello`, press `backspace` will delete `o` character, how do you delete the new  line?

**Comment by stefnotch** [comment]
https://www.computerhope.com/cdn/keyboard/delete.jpg
You have to press this `DEL`ete key

**Comment by Jocs** [comment]
@stefnotch I think this a new feature, we have not implement yet. thanks!

**Comment by Joshuasony** [comment]
Hi there, got the same issue, I think. Pretty strange behavior in my opinion. 
[Here is a video](https://www.dropbox.com/s/qtsdj7f9qk66rzh/marktext_bug.mov?dl=0) showing the strange behavior. Right now, I can endlessly forward-delete a line.

My expectation is, that  the I can forward-delete characters so that the deleted line then won't be copied.

**Comment by Jocs** [comment]
@Joshuasony Thanks for your reporting this issue, we will pay attention to this issue and fix it as soon as possible.
