### ISSUE TITLE
Possible Dataloss after using copy-feature

### ISSUE THREAD

**Issue by ixidion** [marktext/marktext#3018]
### Description

After copying and pasting a file to the same folder, the original file is deleted. A new file has not been created. This happens with a [cryptomator 1.6.5](https://cryptomator.org/)/dokany folder. With a regular folder I get the message source/destination must not be the same. It seems like the check is implemented in a strange way and not working always as expected.

- [x] Can you reproduce the issue? 

### Steps to reproduce
1. Create a file
2. copy the file
3. paste it to the same directory

**Expected behavior:**
A new file is created with a suffix "copy" or something like that.

**Actual behavior:**
Original file is deleted and kept open. Message: "{filename} has been removed on disk." Luckily the file stays open and can be saved, otherwise it would be lost.

**Link to an example: [optional]**

### Versions

- MarkText version: 0.16.3
- Operating system: Windows 10
- Cryptomator 1.6.5
- Dokany 1.5.1.1000

**Comment by ixidion** [comment]
In addition: The command "move to trash" doesn't work with a file on an encrypted folder. No error, file is not deleted.

**Comment by ixidion** [comment]
Also see: https://community.cryptomator.org/t/electron-javascript-app-causes-data-loss-with-cryptomator/9476

**Comment by fxha** [comment]
We'll add better UX by providing more checks for edge cases and report more errors in our next release.

> After copying and pasting a file to the same folder, the original file is deleted.

We prevented this by checking for this case before executing the action, but the core issue is most likely Cryptomator because the filesystem shouldn't delete `src` and try to copy the contents from `src` that was deleted in the same filesystem call.

> The command "move to trash" doesn't work with a file on an encrypted folder. No error, file is not deleted.

The error message is now shown to the user. I guess that Cryptomator forbid to move the file from the unencrypted filesystem into the OS trash.
