### ISSUE TITLE
Heading Key binding doesn't work

### ISSUE THREAD

**Issue by kewtgh** [marktext/marktext#3038]
### Description

Heading Key binding doesn't work. Others' are OK. But only Heading Key binding doesn't work.
Only happened on version 0.17.0-rc.1. Version 0.16.3 is working well.
Other Key bindings are working well. I've tried CTRL+B (Bold), and CTRL+Shift+T (Table).

- [ ] Can you reproduce the issue? 

1. At any paragraph or heading, press CTRL+Num or CTRL+Shift+Num.

**Expected behavior:**

When pressing the keyboard shortcuts, heading will change to expected level. 

**Actual behavior:**

Nothing happened.

### Versions

- MarkText version: 0.17.0-rc.1.
- Operating system:Win11

**Comment by fxha** [comment]
@kewtgh Unfortunately, we had to remove the defaut key bindings on Windows because we changed the `Ctrl+Shift+<number>` interpretation to support non-US keyboards. If you like, you can bind these actions to any key via settings "Key Bindings" tab. We still have a default binding on macOS and Linux because we have access to a larger set of key bindings.
