### ISSUE TITLE
Creating a empty fenced code block within a list

### ISSUE THREAD

**Issue by stefnotch** [marktext/marktext#315]
### Description

Creating a empty fenced code block within a list creates another list item

### Steps to reproduce

1. Type `- ` to create a list
2. Type 3 backticks (`) to create a fenced code block (Don't type a language)
3. Hit Enter:
![image](https://user-images.githubusercontent.com/10220080/40778873-08628228-64d3-11e8-91f9-8721c7920218.png)

**Expected behavior:** It doesn't create another list item.

**Actual behavior:** It created another list item

### Versions

- Mark Text: v 0.11.42
- OS: Windows 10

**Comment by Jocs** [comment]
@stefnotch 

I found this to be the correct editor behavior, because when you enter `-`, enter some characters, and then press `enter button`. This should create another list item. However, in this issue, the previous list item is \```. So when you press enter, you first create a new list item. The editor detects that the previous list item contains \```. Upgrade it to a code block. And let it get the focus. If you enter a language, a pop-up language pops up and you press enter. The behavior of the enter key at this time is to select the language of the code block instead of creating a new list item.

**Comment by stefnotch** [comment]
Ok, makes sense. I suppose there might still be some room for improvement, but I'm not sure what could be done.

So, I'm closing this issue.
