### ISSUE TITLE
Why only .md files are displayed and other files are not displayed？

### ISSUE THREAD

**Issue by danielesk** [marktext/marktext#3153]
### Question description

Why only .md files are displayed and other files are not displayed？

**Comment by fxha** [comment]
This was a design decision to only show supported file types like .md, .txt and other markdown file extensions.

**Comment by poisonborz** [comment]
This is a really user-hostile decision, and should be at least a configurable option to have enabled. I have a number of files that need to have a fixed filename, but they are otherwise simple text files. I can't use MarkText because of that and have to resort to alternative editors. I have never seen any text editor behaving this way - and I've seen a few. 

What is the reasoning here? Typora, Sublime, VSCode will happily open `.doc` files, even `.dll` files, it's not the editor's concern what is readable to the user.

**Comment by mwyschan** [comment]
Sorry to necro a closed issue, but I agree with @poisonborz. I can see the reasoning behind only showing supported files in the `Open File...` menu, but refusing to read the file is another thing entirely. Markdown is just syntax for raw text, the file extension should not affect whether the editor can read a file or not.

In particular, #2109 has been requesting for `.mdx` support since May 2020. At least add support for the one missing markdown file extension.

**Comment by MejanH** [comment]
It would be really great to have support for `.mdx` files. we don't need to support a full preview of `.mdx`. if Marktext sees any comment saying don't generate as HTML code in the editor or something like that in the code then they can just mark the below code as a javascript/react code block. I opened `.mdx` file after renaming it to `.md` file extension. everything seems to be fine. 

I guess we need to change this [function](https://github.com/marktext/marktext/blob/aed36dbf320b17bdd0e44398d5cfe45a4d357940/src/common/filesystem/paths.js#L59)? 
```javascript
/**
 * Returns true if the path is a markdown file or symbolic link to a markdown file.
 *
 * @param {string} filepath The path or link path.
 */
export const isMarkdownFile = filepath => {
  if (!isFile2(filepath)) return false

  // Check symbolic link.
  if (isSymbolicLink(filepath)) {
    const targetPath = path.resolve(path.dirname(filepath), fs.readlinkSync(filepath))
    return isFile(targetPath) && hasMarkdownExtension(targetPath)
  }
  return hasMarkdownExtension(filepath)
}
```

Never tried Electronjs once. if I change this type of checkers in my forked repo then will I be able to save it as `.mdx` file successfully? or does Marktext always save files with `.md` extension whether the file already exists or not?

**Comment by MejanH** [comment]
created a [PR](https://github.com/marktext/marktext/pull/3424) for this. had to go through a lot of build issues for a guy to try electronjs the first time.

`.exe` file: https://drive.google.com/file/d/11GCMLhHpLJ3aJ9-qRLnjTMrV9B0N0ECn/view?usp=sharing
