### ISSUE TITLE
you domain is squatted

### ISSUE THREAD

**Issue by CouldBeThis** [marktext/marktext#3348]
[Marktext.app is for sale! | Bodis.com - Smart Domain Monetization](https://marktext.app/)

![image](https://user-images.githubusercontent.com/53547181/179174110-420fa41f-1af1-486b-b979-1c4c7dcb24c6.png)

Edit: Duplicate of marktext/website#66

**Comment by fxha** [comment]
We can remove the links from the repository and eventually release a new version but are currently unable to remove the links from the MarkText organization and repository description without help from @Jocs.

If you have contact to GitHub employees, please forward ticket nr. 1702624 which should discuss this topic. Otherwise we need to hope that this free support ticket will be processed at some day.

**Comment by Jocs** [comment]
The new official website is already available, https://www.marktext.cc/
