### ISSUE TITLE
Pasting only the link

### ISSUE THREAD

**Issue by CsatiZoltan** [marktext/marktext#3450]
When I copy a link and paste it, it automatically inserts a description as well. How can I disable this behaviour? There is a context menu item "Paste as Plain Text", but I would like that behaviour for pasting from the keyboard too.

**Comment by CsatiZoltan** [comment]
It was a macOS-related issue.

**Comment by debsidian** [comment]
> It was a macOS-related issue.

I have this same issue on Fedora 37. It is not just a macOS-related issue.

I agree with OP, it is super annoying when copying a url via keyboard shortcut to have additional stuff, other than what you are copying, appearing in the Editor. You have to go back and manually delete the auto-pasted `title-tag` text and most times, it's just faster to manually type in a url into MarkText, regardless of how long it is. Ultimately, it's less of a PITA than dealing with the auto-pasted title tag text.

This bug is the main reason why I use Typora if I find myself needing to copy/paste any url links (which is most times).
