### ISSUE TITLE
[bug] Container blocks (block quotes, nested lists), wrong newline insertion

### ISSUE THREAD

**Issue by gitfineon** [marktext/marktext#408]
### Description

1. Leaving "Source Code Mode" does automatically insert newlines to (nested) lists, which might be feature in your opinion, but it manipulates existing code, which is fine within the GFM spec.
2. A similar problem exists for lists nested in block quotes. But it is even worse here, because removing the newlines in "Source Code Mode" inserts block quotes recursively **and** adds newlines which makes each line quoted on level lower for each switch back from "Source Code Mode"
3. Just saw that in default writing mode, every list has this huge paragraph space between each item. This should not be the default behavior.
4. There should be no newline required, before the first list item, but the leaving "Source Code Mode" automatically inserts a newline
5. horizontal rule `---` gets quoted (minor bug)

### Steps to reproduce

1. Switch to "Source Code Mode"
2. Insert
```
**Expected behavior:**

---
This is a test file
* outer list item 1
* outer list item 2
  * inner list item 1
  * inner list item 2
* outer list item 3

* outer list item 4

following text which should not have indent
* next list item 1
* next list item 1
- separated final list item 1
- separated final list item 2

> quoted list
> * qlist item 1
> * qlist item 2
> * qlist item 3
---
```
3. Leave "Source Code Mode"

#### Preview using GitHub
**Expected behavior:**

---
This is a test file
* outer list item 1
* outer list item 2
  * inner list item 1
  * inner list item 2
* outer list item 3

* outer list item 4

following text which should not have indent
* next list item 1
* next list item 1
- separated final list item 1
- separated final list item 2

> quoted list
> * qlist item 1
> * qlist item 2
> * qlist item 3
---

#### Modified Source
**Actual behavior:**
``` html
**Expected behavior:**

---
<!-- inserted newline bug -->
This is a test file
<!-- inserted newline bug -->
* outer list item 1
<!-- inserted newline feature imho bug -->
* outer list item 2
<!-- inserted newline feature imho bug -->
  * inner list item 1
  * inner list item 2
<!-- inserted newline feature imho bug -->
* outer list item 3

* outer list item 4

following text which should not have indent
<!-- inserted newline bug -->
* next list item 1
* next list item 1
* separated final list item 1<!-- replaced bullet list marker bug -->
* separated final list item 2<!-- replaced bullet list marker bug -->

> quoted list
> 
> * qlist item 1
>   
>   > * qlist item 2
>   >   
>   >   > > * qlist item 3
> 
> --- <!-- horizontal rule was not quoted before bug -->
```
The "separated final" list should start a new list because of the changed marker and separated by a par space.

For the quoted list example you have to switch back to "Source Code Mode" multiple times

### Versions

- Mark Text: v 0.12.25 (installed via flatpak)
- OS: Ubuntu 18.04 LTS (Linux 4.15)

**Comment by fxha** [comment]
Thanks @gitfineon.

> but it manipulates existing code

Sorry, but currently there is no option to disable automatic formatting.

> Just saw that in default writing mode, every list has this huge paragraph space between each item. This should not be the default behavior.

You can change the behaviour in settings. I don't see any problems with that, but let's see if others  have the same problem too. It's also the default behaviour in many office suites.

### Mixed list types

> This is a test file
> * outer list item 1
> * outer list item 2
>   * inner list item 1
>   * inner list item 2
> * outer list item 3
> 
> * outer list item 4

Exactly as expected; if you mix tight and loose list items at the same level, it will be converted to loose items.

The nested list items are tight items but the outer list is loose, so you see a  pitch between the outer and nested list.

### Blockquotes and list items

> A similar problem exists for lists nested in block quotes. But it is even worse here, because removing the newlines in "Source Code Mode" inserts block quotes recursively and adds newlines which makes each line quoted on level lower for each switch back from "Source Code Mode"

Yes this is definitely a bug.

### Mixed list marker and no new line between paragraph and new line

> following text which should not have indent
> * next list item 1
> * next list item 1
> - separated final list item 1
> - separated final list item 2

> There should be no newline required, before the first list item, but the leaving "Source Code Mode" automatically inserts a newline

According to GFM example [GFM #274](https://github.github.com/gfm/#example-274) and [GFM #276](https://github.github.com/gfm/#example-276) this is correct. I thought that was not allowed because markdown have to be separated through one/two new line(s). But maybe conflict/problem with [example 277](https://github.github.com/gfm/#example-277). So a bug too, but need discussion.

### Thematic breaks (---)

Yes, thematic breaks can interrupt a paragraph [#28 and #29](https://github.github.com/gfm/#example-28).

### Thematic break and blockquotes

> horizontal rule `---` gets quoted

I'm unsure but I think you cannot interrupt a blockquote with thematic breaks. It needs a new line between blockquote and  `---`. But also strange why it gets quoted, maybe a bug too?

**Comment by fxha** [comment]
@gitfineon All issues has been fixed but we still insert a new line to normalize the markdown document. Your document and the document below are equivalent according CommonMark and GFM:

```markdown
**Expected behavior:**

---

This is a test file

* outer list item 1

* outer list item 2
  
  * inner list item 1
  * inner list item 2

* outer list item 3

* outer list item 4

following text which should not have indent

* next list item 1
* next list item 1
- separated final list item 1
- separated final list item 2

> quoted list
> 
> * qlist item 1
> * qlist item 2
> * qlist item 3

---
```

Perhaps we will fix/disable automatically document formatting later.
