### ISSUE TITLE
Windows installer is detected as Malware/suspicious by Anti-Virus

### ISSUE THREAD

**Issue by cakkac** [marktext/marktext#418]
### Description

Detected as Malware/suspicious by Anti-Virus on Windows

### Steps to reproduce

1. Download installer for Windows (.exe)
2. Launch installer and Anti-Virus (McAfee) is blocking the installer

Uploaded the .exe on Reverse.it to check the relevance, and it is indicated as Malicious 75/100, here the result:
https://www.reverse.it/sample/cd69716f83a40d16cd72993c0f60ae9cf02c343489a21424707e860d67711e28

### Versions

- Mark Text: 0.12.25
- OS: Windows 10

**Comment by SuperSandro2000** [comment]
1st known, 2nd virustotal.com shows 1/66 and never heard that antivirus name. Compile from source if you don't believe the dev. He should probably submit it to Microsoft to unflag it.

**Comment by fxha** [comment]
The setup might look dangerous to some AV's because it's packed as a 7zip archive with an unpack payload - like other applications too. At the moment there's nothing we can do to solve the problem.

In additional the only false positive result is from "Bkav". I never heard of the company but if you have problems with your AV, you can submit a false positive report. Many AV's support some sort of submission to report viruses or false positives.

> Uploaded the .exe on Reverse.it to check the relevance, and it is indicated as Malicious 75/100, here the result:

I tested it with the latest firefox setup for windows and it has a 100% threat score.

**Comment by keito940** [comment]
Append issue report.
I using Trend Micro is Detected to malware.

**Comment by SuperSandro2000** [comment]
@keito940 Use some reputable AV or trust VirusTotal.com
