### ISSUE TITLE
Feature request: snap version

### ISSUE THREAD

**Issue by nicocarbone** [marktext/marktext#452]
Hello.

Great job with MarkText, it is really well done and works perfectly for my needs.

My question: have you considered releasing it as snap?
I know there is a flatpak version and is the one I am using in my Ubuntu installation. But I think snaps have some advantages:

- Transparent and automated updates. 
- Integration with Gnome Software in its default form in Ubuntu (without the need of installing extra packages)

Thanks you!

**Comment by fxha** [comment]
Thanks @nicocarbone, yes we had a snap package (not hosted by Canonical) but we had several issues to deal with and decided to use flatpak instead. In short: it worked on Ubuntu (maybe all Debian distros) but that's it.

> Integration with Gnome Software in its default form in Ubuntu (without the need of installing extra packages)

Yes that's true because snappy is a Canonical ("Ubuntu") product but that does not apply to other distros aswell.

Extract from the old Linux installation instructions:

> ## Snappy
> 
> Downlaod snap file and execute `sudo snap install --classic --dangerous marktext_%version%_amd64.snap`.
> 
> Please note that snappy packages may not work on not Debian-based distros and SELinux distros.
> 
> ### Known issues
> 
> - Library problems on SELinux distros (even if SELinux is disabled) and not Debian-based distros.
> - User directories (like documents and downloads) are always saved under the english directory name.
>- IBus problem with `fcitx`

If you want to fix the issues above or someone else then we can talk about it but the easiest is to use and support the flatpak/appimage packages.

**Comment by nicocarbone** [comment]
I understand.
I am not very experienced in snap packaging, but is something I would like to dive into eventually. If you like, I could give it a try and see what happens.
I do understand that to leverage all the benefits of snaps they need to be hosted in snapcraft (by Canonical). Was there any particular reason why you choose not to host Mark Text on it?

**Comment by fxha** [comment]
> I am not very experienced in snap packaging, but is something I would like to dive into eventually. If you like, I could give it a try and see what happens.

Yes, sure. @Jocs What's your opinion?

> I do understand that to leverage all the benefits of snaps they need to be hosted in snapcraft (by Canonical). Was there any particular reason why you choose not to host Mark Text on it?

Mark Text is still in development and we released binaries so everyone can use them. Because of the problems above and I don't have experience with snap packages and/or hosting, I decide to move to flatpak because it's more convenient - my own opinion. Also we had to use the `--classic` parameter to get access to the host system (like `/mnt`, `/dev` etc).

**Comment by nicocarbone** [comment]
> I decide to move to flatpak because it's more convenient - my own opinion. Also we had to use the --classic parameter to get access to the host system (like /mnt, /dev etc).
The host system can be accessed without classic confinement by requesting the appropriate interface (permission).

Ok, I'll wait for @Jocs opinion.

**Comment by queeup** [comment]
Is it possible to consider snap package again? Snaps are working all distros now.

**Comment by fxha** [comment]
@queeup It's not planned as we already got flatpak and Linux installers (deb/rpm). Please feel free to create a community driven snap package.

**Comment by NucciTheBoss** [comment]
Not to reopen the issue, but there is now a functional snap package on the Snap Store. The package is in the process of being accepted into the Snapcrafters organization (community members who build and maintain snaps), and there is an open call for testing out for the beta version of the package. You can install the snap package like so:

```bash
sudo snap install marktext --beta
```

If you encounter any issues with the package, you can get in contact with the package developers using the contact links on the package page here: https://snapcraft.io/marktext
