### ISSUE TITLE
Feature request: separate font for code blocks

### ISSUE THREAD

**Issue by esthomw** [marktext/marktext#467]
### Description

Configuration option to change font style for code blocks. E.g. using Fira Code monospaced font with code ligatures instead of default for whole document.

**Expected behavior:** 

If changed in configuration option a different font family should be displayed for code blocks.

**Actual behavior:**

At the moment font in code blocks needs to be identical as the default font for the whole document. Changing font to more code oriented breaks the aesthetics of the text outside code blocks.

**Comment by fxha** [comment]
@esthomw It's not a duplicate, we talked in #373 about the source code view (CodeMirror) and not about code blocks - so a PR is welcome.

I don't know which default font is the "best" font but please set `monospace` as fallback font. I think `Fira Mono` is a good pick as default font but not the `Fira Code` because it merges some characters. Then add a Google Fonts import url like here:

https://github.com/marktext/marktext/blob/d1be68372f53305cd7564b31dc98ab31d73c99f6/src/muya/themes/light.css#L1

**Comment by Jocs** [comment]
@esthomw Do you still need this feature ? we have rewrite the code block.

**Comment by fxha** [comment]
@Jocs  Why can we not simply add a custom css style?
