### ISSUE TITLE
Future Request: Support Pandoc

### ISSUE THREAD

**Issue by keito940** [marktext/marktext#472]
### Description

Hi. keito940.
Pandoc is a useful tool to convert to various document files, but it seems that Mark Text does not support it now.
If you support Pandoc you can also support markdown for Pandoc
If Pandoc is supported, it will be compatible with text files other than HTML and PDF (of course, with specifications that can be used without Pandoc) and can be converted to various document files.
So please support.

### Versions

- Mark Text:v0.12.25
- OS: Windows 10

**Comment by Jocs** [comment]
Very good advice, we also have plans to support pandoc. Just because development time is limited, there is currently no support.

**Comment by fxha** [comment]
@Jocs Do you plan to support `pandoc` for export too? For example `LaTeX` or `docx`. It might be a problem with not standardized markdown elements.

**Comment by anishmittal2020** [comment]
Hi, is Pandoc supported? Please clarify.

**Comment by fxha** [comment]
@anishmittal2020 Yes, you can import files like Word documents but exporting is not yet supported via GUI. `pandoc` is required and must be set in the environment path. The flatpak package is an exception and doesn't support `pandoc` yet or you have to manually add `pandoc` to the sandbox.

**Full List:**

```
  'html',
  'docx',
  'latex',
  'tex',
  'ltx',
  'rst',
  'rest',
  'org',
  'wiki',
  'dokuwiki',
  'textile',
  'opml',
  'epub'
```

OK, we have to update the file extension list soon, for example because OpenOffice/LibreOffice is missing.

**Comment by fxha** [comment]
> to render the markdown as html inside the editor

So you can see HTML instead of markdown, for example in the source code mode? What would be the benefits for doing so? BTW you can always use HTML in markdown documents ([raw HTML](https://github.github.com/gfm/#raw-html) and [HTML blocks](https://github.github.com/gfm/#html-blocks)).
