### ISSUE TITLE
Installation with brew requires sudo

### ISSUE THREAD

**Issue by rob-nash** [marktext/marktext#493]
### Versions

High Sierra 10.13.6

Homebrew 1.7.4
Homebrew/homebrew-core (git revision 3c0f4; last commit 2018-09-12)
Homebrew/homebrew-cask (git revision 1172; last commit 2018-09-12)

```bash
$ brew cask install mark-text
==> Satisfying dependencies
==> Downloading https://github.com/marktext/marktext/releases/download/v0.12.25/marktext-0.12.25.dmg
Already downloaded: /Users/robertnash/Library/Caches/Homebrew/downloads/4a1b00a7011cfa96cde0e3911dcc10968647122741e37c1a868e8d4b050b13a3--marktext-0.12.25.dmg
==> Verifying SHA-256 checksum for Cask 'mark-text'.
==> Installing Cask mark-text
==> Creating Caskroom at /usr/local/Caskroom
==> We'll set permissions properly so we won't need sudo in the future.
Password:
```

Also tried this but no change.

```bash
$ export HOMEBREW_CASK_OPTS="--appdir=$HOME/.cask"
$ brew update
Already up-to-date.
```

I realise this is an issue with brew but is there something that can be changed here so that brew doesn't need sudo ?

**Comment by Jocs** [comment]
@rob-nash Maybe it's related to where you installed your home brew?

**Comment by rob-nash** [comment]
I used this script

```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by saivan** [comment]
Yea, I just tried this; I don't need sudo. I think your cask configuration might be off somehow.

**Comment by rob-nash** [comment]
I installed brew moments before attempting to install marktext. I installed brew using the following script which is the default method brew recommends on their [website](http://brew.sh)

```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

My brew setup is as default as it gets.

**Comment by rob-nash** [comment]
☹️

**Comment by Jocs** [comment]
@rob-nash I closed this issue, Because I think it's not problem of Mark Text. I installed homebrew as the recommends way.

```sh
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

then:

```sh
brew cask install mark-text
```

![1](https://user-images.githubusercontent.com/9712830/47489178-93137080-d878-11e8-80bd-63ecf9d47a81.jpg)

![2](https://user-images.githubusercontent.com/9712830/47489191-9a3a7e80-d878-11e8-9f44-576b0652fa77.jpg)

**Comment by Jocs** [comment]
@rob-nash download the latest version in the release page? we just released the new version.

**Comment by fxha** [comment]
@rob-nash I think it's a configuration problem too. Maybe [Permission denied error](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/permission_denied_error_fix_appdir.md) will help you or can you run the comand with `--verbose` or `-v` like `brew command [--verbose|-v] [options] [formula] …`.

There is one difference; @Jocs's brew installation path is `/Applications` instead of `/usr/local/Caskroom` and `/usr/local` should be owned by `root`.
