### ISSUE TITLE
Add keyboard shortcut for adding table rows

### ISSUE THREAD

**Issue by tmr232** [marktext/marktext#563]
### Describe your feature request

Add a keyboard shortcut for adding table rows. Possible common options are:

1. `Tab` at the last column of last row in table creates a new row and moves to it
2. `Return` (possibly with added modifier) creates a row below the current one and moves to it.

### What problem does this feature solve? [optional]

Currently, adding table rows is very cumbersome, requiring mouse interaction.

**Comment by Jocs** [comment]
@tmr232 we already has a keyboard shortcut to add table row. `Cmd` + `Enter`. try to use it?

**Comment by tmr232** [comment]
I'm not sure what `Cmd` would translate to on Linux, but I tried the following:
`Ctrl` + `Enter` --> Cursor moves below the table
`Shift` + `Enter` --> `<br/>` is added
`Alt` + `Enter` --> Same as `Ctrl` + `Enter`

**Comment by fxha** [comment]
> `Tab` at the last column of last row in table creates a new row and moves to it

I think that this feature is a little bit problematic because it could confuse the user. I mean, I wouldn't expect such a behavior.

> I'm not sure what Cmd would translate to on Linux

It's normally `Ctrl+Enter` but to insert a new row you have to use the meta key `Super`/`Win` and `Enter`.

https://github.com/marktext/marktext/blob/387d42822de38639b5c677b4000529d2a3be1166/src/muya/lib/contentState/enterCtrl.js#L260

**Comment by tmr232** [comment]
Thanks, that seems to do it.
 I'd never have thought of trying the `Win` key for it. Seems like an odd choice to me.

**Comment by fxha** [comment]
@tmr232  Yes, that is true.

@Jocs Is there a particular reason why you use the meta key? `CmdOrCltr+Enter` should be available, right?
