### ISSUE TITLE
Whole select can not be canceled

### ISSUE THREAD

**Issue by Aecu** [marktext/marktext#613]
### Description

When i press ctrl + a for whole select , then the onLbuttondown does not work

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Insert following text:

```
# a

b

c
```

2. Ctrl + A
3. Lbuttondown

**Expected behavior:**
move caret to specific position

**Actual behavior:**
Nothing happened, the whole select state can not be canceled.

- Operating system: Win7

**Comment by fxha** [comment]
Thanks @Aecu, I can reproduce the issue but only with a larger document.

**Comment by H16Y** [comment]
@fxha actually, if the file content contains titles (lines starting with (several) "#"), and then I press Ctrl+A, the selection cannot be cleared by clicking somewhere. The only way to clear is to use "up", "down", "left", or "right" on keyboard.
I think it is a bug, since if I enter plain text, the selection can always be cleared by clicking.
