### ISSUE TITLE
Copy pasting image directly from clipboard to markdown file

### ISSUE THREAD

**Issue by dotm** [marktext/marktext#627]
### Describe your feature request

Is it possible to directly copy-paste image from clipboard to markdown file using MarkText? Is this already implemented?

Steps:

- Copy image to clipboard (using Ctrl+C, Windows' Snipping Tool/Screenshot, or Mac's Cmd+Shift+4)
- Go to a markdown file in MarkText
- Ctrl+V
- File is automatically uploaded or stored in an asset directory (relative to the markdown file or in a dedicated directory for MarkText)
- Link is automatically pasted to markdown file: `![xxx](link/to/image)`

### What problem does this feature solve? [optional]

I often add screenshot of math formula, illustration, etc. to my note and it's a pain to manually upload things every time I add them. This is the only thing that ties me to Evernote...

### Additional context [optional]

I'm a mid-level javascript developer. I'd be happy to contribute for this feature if the maintainers are busy doing other things. If any maintainer can point me to the right files/resources, it'd be really helpful.

Thanks

**Comment by fxha** [comment]
This is a really useful feature but the problem is that our backend `muya` is pure Javascript, so we can use it in a normal web browsers, and we don't have access to the local filesystem nor the clipboard data. We would need a "portal"/blocking event to Electron to access the desktop clipboard or implement it as plugin. In fact, I would prefer a plugin because it would be much less work because then we can use Electron to get the data.

You can find the paste handler here:

https://github.com/marktext/marktext/blob/c169a7704eb77298e4ae479951619f0b914ff277/src/muya/lib/contentState/pasteCtrl.js#L69

Let us see if we can add a temporary solution until we support plugins.

**Comment by Jocs** [comment]
@dotm It's a useful feature, we'll take it into consideration when we refactor `muya`.

**Comment by Rishgod** [comment]
this does not work of you want to add more than one image file!

**Comment by ranjithmkumar** [comment]
Sorry. May I know what is the current state of this feature?

**Comment by spdebbarma** [comment]
Just passing by, trying to figure out how to implement this on my own on a personal project.

**Comment by ldraney** [comment]
This would be a very useful feature

**Comment by syedamaann** [comment]
Hey, what's the currents state of this feature? If not, I'd like to contribute in this if directed to the right resources.
