### ISSUE TITLE
Saving Crashes Marktext

### ISSUE THREAD

**Issue by Aurathic** [marktext/marktext#642]
### Description

When I attempt to save any file, Marktext closes without giving any sort of error message.

### Steps to reproduce

1. Open Marktext 
2. Do anything you want.
3. Press 'Ctrl' and 'S' or 'Ctrl' + 'Shift' + 'S' simultaneously

**Expected behavior:**
A dialog box would open allowing saving of the open document.

**Actual behavior:**
The program silently and immediately crashes.

### Versions

- Mark Text: 0.13.65
- Operating system: Linux Mint 19.1, XFCE 64-bit

**Comment by fxha** [comment]
Thanks @Aurathic, as you can imagine we cannot reproduce the problem. Normally Mark Text show an error dialog and should not exit immediately. Therefore I assume a fatal application/system crash that cannot be handled. Is it possible to save via menu and can you please provide futher imformation like:

- ls the native save dialog displayed (before the crash)?
- Have you permission to save to the selected location?
- Which package do you use? Flatpak, AppImage, build from source, etc?
- Could  you please launch Mark Text from terminal and see which messages appear while saving?
- Can you open a file via menu? If not, can you please try to open a file via command line? Like `marktext %file%`?
-  Is it possible to build Mark Text from `master` because we added an improved error handler but I suspect that will not help either.
- Logs are saved to `~/.config/marktext/error.log` or somewhere in `~/.var/` for Flatpak - I guess

I personally running Mark Text on Fedora (`wayland`) with GNOME DE and also have it tested with `Xorg/X11`, so I suspect some critical system or dependency conflicts.

**Comment by MiguelNiblock** [comment]
Here's what I tried...
* The crash happens as soon as I click on save from the file menu.
* It crashes before I select the save location.
* Using the app from the Mint Software Center. v 0.13.65
* Open file from menu also crashes in the same way. Running marktext from the command line gives me: `marktext: command not found`. I imagine it's because of installing it through the software center?
* I don't know how to install from master...
* I went to .config folder and there was no marktext directory.

**Comment by fxha** [comment]
@Aurathic @MiguelNiblock The problem has been fixed and is available via flatpak. Please update flatpak with the following command:

```
$ sudo flatpak update
Looking for updates...
Updating in system:
org.freedesktop.Platform/x86_64/18.08              flathub 5ff8a9d6f9a6
org.freedesktop.Sdk/x86_64/18.08                   flathub c3f62b801fec
[...]
Is this ok [y/n]: y
```

After the update of `org.freedesktop.Platform` and `org.freedesktop.Sdk` everything should work as expected.
