### ISSUE TITLE
multiple empty line  saved but disappear when next time open file

### ISSUE THREAD

**Issue by dujuncheng** [marktext/marktext#644]
### Description

- [x] Can you reproduce the issue? 
yes 

### Steps to reproduce

1. open markText , and write something with multiple empty lines , likes 
```
content1111 


content222 
```

2. save this file, and reopen this file
3. you will find that the multiple empty lines disappear, what you get will be like below:
```
content1111 
content222 
```

**Expected behavior:**

I expected the next time I reopen the file with multiple empty lines, the empty lines still exist.

**Actual behavior:**

the empty lines disapear

**Link to an example: [optional]**

### Versions

- Mark Text: v 0.13.65
- Operating system: macos  10.14.1 (18B75)

**Comment by fxha** [comment]
Thanks @dujuncheng, according to CommonMark Spec and GitHub Flavored Markdown Spec it's the expected behavior:

> 4.8 Paragraphs 
> [...]
> Multiple blank lines between paragraph have no effect.

But you can always use HTML tags like `<br>` to break a line. We will fix the inconsistent saving bug in a later version of Mark Text because the current backend don't allow us to fix it easily without breaking the editor.
