### ISSUE TITLE
MarkText licensing and sharing files

### ISSUE THREAD

**Issue by Daniil77177** [marktext/marktext#664]
# Licensing and sharing
Can I use screenshot and exported docs of MarkText for post it on Twitter or any other resource (_without_  logo or any attribution)? And can I use it to create and share my articles (_again without_  attribution, links, information or anything else).

Answer, please on questions upper and this question:

1. Attribution is required?

2. It's absolutely free program?

3. I can use it for any purpose?

4. Why this app is free? What is your benefit?

5. MarkText fully licensed on MIT, and if I'll share files, license share with files?

Hope for fast answer, because your app is greatest for taking math notes.
With best regards, Daniil77177

**Comment by Jocs** [comment]
>Can I use screenshot and exported docs of MarkText for post it on Twitter or any other resource (without logo or any attribution)? 

Yes, you can use it for any reason.

>Attribution is required?
>It's absolutely free program?

Yes, this is a completely open source and free software.

>I can use it for any purpose?

Yes, you can use it for individuals and businesses, but if you want to use it for business purposes, please contact me in advance.

Why this app is free? What is your benefit?

I have already mentioned in the readme that this software is due to personal hobbies, to do a favorite Markdown editor, and also want to share it with Markdown fans, it is always free, of course, I also hope You can sponsor Mark Text to get more contributors involved, and Mark Text may need some server resources later, as well as  put Mark Text on App Store, which cost some money.

MarkText fully licensed on MIT, and if I'll share files, license share with files?

Yes, you can use the files or code in Mark Text. If it is for commercial purposes, please contact me in advance.

**Comment by Daniil77177** [comment]
@Jocs So, attribution is strictly required?

**Comment by Jocs** [comment]
@Daniil77177 Sorry, what's the exactly meaning of `attribution required`?

**Comment by fxha** [comment]
@Daniil77177  You have to distinguish between source code files and your markdown files.

Mark Text as a project/source code files are covered by the MIT license and you have to follow the license restrictions. So, yes you have to credit the copyright holder(s).

Markdown files that you create, edit or export with Mark Text are not converted by the MIT license because Mark Text is only a tool to edit these documents. Meaning you don't have to credit Mark Text.
